### ISSUE TITLE
How to use environment variable in distribution config file

### ISSUE THREAD

**Issue by farmerworking** [docker/distribution#1039]
The scenario is that
1. I run distribution in containerA and redis in containerB
2. distribution use redis as cache
3. I use docker-compose for service management and link these two service together

However the traditional environment variable exposed by docker-compose doesn't match the override rule of distribution so if distribution support reference environment variable directly in configuration file it will be easy to deal with this scenario

**Comment by RichardScothern** [comment]
@farmerworking the idea is to define the registry environmental variables in the docker compose yml file.   Variables set under the `environment` section will be visible in the container.

**Comment by farmerworking** [comment]
contents in docker-compose.yml

    registry:
        image: registry:2
        links:
            - cache
    cache:
        image: redis

the cache addr and port will be available at runtime and will be something like CACHE_PORT_6379_TCP_ADDR, CACHE_PORT_6379_TCP_PORT. However this information is dynamic which can't be defined under ``environment`` section

@RichardScothern

**Comment by RichardScothern** [comment]
You have to name your environment variables in a specific manner described here:
https://github.com/docker/distribution/blob/master/docs/configuration.md#override-specific-configuration-options

Your issue is more specific to docker compose.  I am unsure if you can interpolate environment variables in the compose file - I suggest asking your question in the #docker-compose IRC channel.
