### ISSUE TITLE
Layer verification error being reporting as 500

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#112]
The details are light but the incorrect error code may be returned when a layer fails tarsum verification during upload. Currently, a 500 status is being returned with an UNKNOWN error code. This should return a DIGEST_INVALID error.
 
Please see daemon log here for error status: https://www.irccloud.com/pastebin/etWhnm4s

Note there may be another bug here in that we don't expect for the content to be invalid on upload.

cc @dmcgowan @tiborvass

**Comment by tiborvass** [comment]
In order to test the bug, here's what I did on the docker repo:

```
$ make shell
...
# cat registry-config.yaml
version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /registry
http:
  addr: 127.0.0.1:8080
# ./project/make.sh binary
# export PATH=/go/src/github.com/docker/docker/bundles/$(cat VERSION)/binary:$PATH
# docker -d -D &>/tmp/docker.log &
# /go/bin/registry-v2 registry-config.yaml &>/tmp/registry.log &
# cat <<EOF | docker build -t 127.0.0.1:8080/user/test
from busybox
run ls
EOF
...
# docker push 127.0.0.1:8080/user/test
511136ea3c5a: Image push failed
FATA[0000] Error pushing to registry: Server error: 500 trying to push user/test blob - tarsum.v1+sha256:eab7fe9f231cc993c405151ea1e0bde78f42bd076b2be0c30839074ee4b7e279
```

I wonder whether it has something to do with the old scratch image `511136ea3c5a...`

**Comment by stevvooe** [comment]
@tiborvass Could you tar up the contents of "/registry" and the tarfile generated by `docker save <problem image>` and send it to me (or attach to this ticket, somehow)? I am going to check the state of the uploads directory and see what data was actually flushed. At the same time, I'll compare against what is in the docker save tar.

**Comment by tiborvass** [comment]
@stevvooe https://slack-files.com/T026DFMG3-F03G65Z10-897235e8cb

**Comment by stevvooe** [comment]
Looks like there is a difference in the tarsum calculation result between the client and registry. My local registry and client are getting the following:

     1024 bytes tarsum.v1+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Interestingly enough, the provided registry tar received the complete data (tarsum calculated with https://gist.github.com/stevvooe/4bef23c2ab7e2f273c3b):

    tarsum.v1+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855	registry-folder/docker/registry/v2/repositories/user/test/uploads/2a6fec09-1572-4085-afe6-87c90089fd4b/data

However, the provided push logs are showing the following tarsum being pushed:

    tarsum.v1+sha256:eab7fe9f231cc993c405151ea1e0bde78f42bd076b2be0c30839074ee4b7e279

I think we may have a bug on the client that may be causing this.

**Comment by tiborvass** [comment]
I confirm that docker#10230 broke this. Prior to that PR i can push to my local registry.

Are there additional checks to do on the registry? or is it totally my/our fault?

**Comment by stevvooe** [comment]
@tiborvass The registry should not return a 500. It's supposed to notify the client that the digest was invalid and the upload failed, with a 400 status.

I'd still like to understand where the invalid tarsum came from. Admittedly, I don't quite understand docker/docker#10230's relation to this issue.

Thanks for providing the debugging data.

**Comment by jlhawn** [comment]
So I've tracked down the cause of the issue!

The `scratch` layer (ID `511136e....2c158`) that exists in just about *every* image ever made is **not** actually an empty tar archive. It contains a single entry:

    ./

an empty directory. When this archive is extracted no changes are really made, but when it is installed in Docker the checksum computed for this archive is `tarsum.v1+sha256:eab7fe9f231cc993c405151ea1e0bde78f42bd076b2be0c30839074ee4b7e279`. HOWEVER when it is exported from the storage driver the `./` entry is not included! So it actually yields an archive without any entries which produces a different tarsum: `tarsum.v1+sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

**Comment by tiborvass** [comment]
That ... is... terrifying...

**Comment by icecrime** [comment]
Nice investigation job! Now if you'll excuse me, I'm going to sit in a corner and cry...

So basically we pull a layer with checksum X, untar it, and taring the result has checksum Y? I guess making the old `scratch` image a real empty tarball would fix it, but is that realistically possible without breaking anything?

**Comment by jlhawn** [comment]
@icecrime 

>  I guess making the old scratch image a real empty tarball would fix it, but is that realistically possible
...

In short, no. This is because that scratch layer exists in more places than just the Docker Hub registry. It exists on probably millions of machines and other v1 registries out there.

For a doable fix, I was thinking that we could use the fact that the registry client can actually compute the checksum while it is uploading the blob, then send the digest at the end in a second request to signal completion of the upload. (@stevvooe correct me if I'm wrong but that's what I got from reading the api docs)

We can take advantage of this and use the checksum from the image JSON file as the "last computed checksum" or "checksum when imported". We can then check to see if this "last known" checksum exists on the registry. If it does, no need to upload! If it doesn't then we have to upload it but in general as we upload the layer it will not have the same checksum as when it was imported. This is perfectly OKAY. Just compute the checksum while we upload it and send along the newly computed checksum and the end of the upload AND save this as the "last known" checksum for that layer. This is the checksum that will go in the manifest. When other registry clients go to download this layer they can still use this "last known" checksum that is in the manifest. Crisis averted.

In a way, it's actually even better that @tiborvass discovered this issue because it means that **we do not have to use Tarsum anymore** (now please excuse me while I dance around joyfully :dancer:). The logic that I described in the previous paragraph is 100% doable with SHA256 or SHA512.

**Comment by jlhawn** [comment]
Oh man... this is great. Smiles everyone :smile: :smile_cat: :smiley: :smiley_cat: :panda_face: :dog:

**Comment by vbatts** [comment]
@jlhawn to some extent, that is true. but the notion of the manifest is to be immutable, and if anything this shows us that we can not guarantee that something about the layer will be mutated on pull<->push. Therefore, if a pull an image, then push it to a local registry, and pull it to another machine, _something_ could change. Then the sums that have been signed are not relevant anymore.
Don't get me wrong, I would love to work on a deterministic `Archive.Tar()` such that we could just rely on linux-utils like `sha256sum` .

**Comment by jlhawn** [comment]
@vbatts 

> the notion of the manifest is to be immutable

This is desired, but we do not, as of now, have a way of guaranteeing this, nor do we have any workflow that currently relies on this to be true. We still have a ways to go before we finalize the manifest format. Today's v2 manifest format is, I think we can all agree, a stop-gap solution until our design matures.

**Comment by icecrime** [comment]
I'm trying to get a good understanding of the issue, and tbh right now I'm a bit skeptical about the proposed fix.

* What I understand of the problem is that `scratch` has this shitty property that `checksum(scratch) != checksum(tar(untar(scratch))`.
* What I understand of the proposed solution is "let's make the client reinterpret what is the *true* checksum for a previously pulled image".

Intuitively, this strikes me as wrong: it's like saying that we trust the registry to serve valid content, but don't trust it with its checkum computation.

**Comment by jlhawn** [comment]
> it's like saying that we trust the registry to serve valid content, but don't trust it with its checkum computation

While we *can* trust the checksum computation that the registry computes, the client *cannot ensure* that it will generate the same archive entries again.

**Comment by stevvooe** [comment]
@tiborvass Would you mind trying out the branch from #121 with your test case? A 400 status code should be thrown, rather than a 500.

**Comment by tiborvass** [comment]
@stevvooe with the version of Docker that was **not** working ?

**Comment by stevvooe** [comment]
@tiborvass Yes, if that's possible. We should ensure the response code is correct. We may have a slight UX issue, in that perhaps the client should have reported the mismatched digest.
