### ISSUE TITLE
Will docker private registry support webhooks for some specified events? 

### ISSUE THREAD

**Issue by cheyang** [docker/distribution#1212]
Webhooks can allow the developers to build or set up integrations which subscribe to certain events on private docker registry. When one of those events is triggered, the private docker registry sends a HTTP POST payload to the webhook's configured URL. For example, When new docker image is pushed to repository, webhooks can be post messages to a chat server or deploy containers to a Kubernetes cluster.

Each webhook can be installed on a specific respository. Once installed, they will be triggered each time a subscribed event occurs on that repository. Can we support this feature?

**Comment by stevvooe** [comment]
[Webhook notifications](https://github.com/docker/distribution/blob/master/docs/notifications.md) have been a part of the registry since the original release. All events are sent by default. Filtration can be easily implemented in a sidecar server.

Please at least look at the documentation before filing such an issue.
