### ISSUE TITLE
Names should encoded in backend storage path

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#124]
There are a number of issues with using repository names directly on the backend. Encoding them as base64 or base32 will prevent many possible problems.

To solve this problem, there are two options:

1. Encode the path names as base32hex (#128).
2. Escape the server-side path components (https://github.com/docker/distribution/issues/124#issuecomment-72531001 and #130).

One of these solutions needs to be selected.

Such a change will break backend compatibility and should block the beta release.

**Comment by dmp42** [comment]
Keeping the storage backend organization clear may be a plus.
So, maybe we can encode just the "2-to-n" patch components?

eg: `dmp42/foo/bar/thing` would go to the storage as `dmp42/09ba6hxxx` ?

**Comment by stevvooe** [comment]
@dmp42 I understand that is a desire but there is not safe way to escape the repository names. It would also be more confusing if it was half-encoded. We'll make a tool in #52 to make listing repositories and mapping paths easy.

**Comment by dmp42** [comment]
Agreed, and fair enough.

**Comment by BrianBland** [comment]
As an alternative to making the repository names more opaque at the storage level, I'd like to suggest having a *hard* separator between the repository names and the storage subpaths, leveraging pathing that is explicitly disallowed by the repository naming scheme.

For instance, a repository name part cannot begin with an internal separator character (`[._-]`). Thus, we could either do one of the following:

1. Add a separator-only path between the repository name and the data storage. Example: `/brianbland/distribution/_/tags/...`
2. Prefix the storage-level pathing with an internal separator. Example: `/brianbland/distribution/_tags/...`.

Both of these prevent a `brianbland/distribution/tags` repository from clobbering the backend storage. We could just as easily use a `.` or `-` as a prefix instead of `_`.

**Comment by stevvooe** [comment]
Option 2 above seems most reasonable. I've added #130 as an alternative to #128.

Let's pick one by the end of the day.

**Comment by dmcgowan** [comment]
I like option 1 since it does not alter either sides of the path.  However keeping every component of the path meaningful is also nice. This decision seems to be more about aesthetics (unless someone can point out a real concern), I vote 2 since Stephen already has a PR.

**Comment by stevvooe** [comment]
@dmcgowan I have a PR out for both solutions (1 - #128, 2 - #130). The goal here is to disallow crafted repository names from providing access to invalid resources. Option 2 would be taken if aesthetics are important enough, barring that we've got the path terminators correct.

**Comment by dmcgowan** [comment]
In that case, I would still prefer option 1 to ensure that the name used by registry cannot be limited by a storage driver.  Needing to escape, partial-encode, use special characters all seem to point to just encode the name and have it be opaque to the storage driver.

@stevvooe is there a real upper name which can be supported by the storage driver?  You mentioned 512 bytes before, what is that referring to.

**Comment by jlhawn** [comment]
I like option 1 because it's future-proof for whatever changes to requirements for the image name are made in the future. The negative things about this is that by intentionally obfuscating the path like this it makes it a bit more difficult to debug and makes the max-key-length limit more of a problem since base64-encoding the path makes the string 33% longer.

However, I would say that the original string isn't really that valuable to debugging at this level of the stack, and the max-key-length constraint is only an issue with some storage backends I believe and can be treated as an orthogonal issue. For these reasons, I'd say I'm more in favor of the encoding option.

**Comment by BrianBland** [comment]
A benefit of leaving the path unaltered is that creating tooling outside of the registry itself becomes an easier task. Specifically, the tree hierarchy of repositories is easy to break down and scan, enabling queries such as "what are all the repositories under the brianbland namespace?"

**Comment by stevvooe** [comment]
After consider the tradeoffs, the least disruptive approach is to merge Option 2, #130. Future proofing is good, but encoding elides a lot of the perceived benefits of having human-readable, hierarchical paths. If we have future problems, we can always encode and migrate the backend.

**Comment by jlhawn** [comment]
SGTM
