### ISSUE TITLE
Status code on missing manifests

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#1291]
Currently testing against the hub setup (token server):
- `pull foo/bar` (<- doesn't exist) will give a 401
- `pull dmp42/bar` (<- doesn't exist & I'm user dmp42) will give a 404

The behavior I would expect is to get a 404 in both scenarios. I should also get a 404 if I try to access an existing resource that I'm not entitled to read.

Whether this is a problem in the registry code, or in the auth server is still somewhat unclear, though the code involved is around: 

https://github.com/docker/distribution/blob/89bedf1e7fdda9f7e8814e4d53947d8116b7a36f/registry/handlers/app.go#L689

https://github.com/docker/distribution/blob/89bedf1e7fdda9f7e8814e4d53947d8116b7a36f/registry/auth/token/accesscontroller.go#L109

cc @RichardScothern @aaronlehmann @BrianBland @bcwalrus

**Comment by aaronlehmann** [comment]
I think this is a registry-side issue and happens because the authorization check is the first thing the dispatcher does (https://github.com/docker/distribution/blob/89bedf1e7fdda9f7e8814e4d53947d8116b7a36f/registry/handlers/app.go#L544), and if it fails, the registry will return a 401 right away, before even checking if the repository exists (https://github.com/docker/distribution/blob/89bedf1e7fdda9f7e8814e4d53947d8116b7a36f/registry/handlers/app.go#L689).

I'm not sure offhand what the right fix is. If we returned 404 instead of 401 in this situation, it might break normal flows (i.e. /v2/ ping). If a special case is needed for specific endpoints like `manifests`, that could get pretty ugly.

**Comment by stevvooe** [comment]
This behavior is correct. If you don't have access to the resource, you get a 401. Arguably, these should be a 403.

If we did do this, we'd have to _always_ return 404 on all access errors.

**Comment by dmp42** [comment]
@stevvooe we can discuss this tomorrow.

Overall I'm inclined to return 404 on both "non-existent resources", and "resources you don't have access to" (<- github is an example of a service that follows this).

Happy to revisit, still.

**Comment by dmcgowan** [comment]
The messaging on this has been fixed around this in the client. There is some differentiating between no access to the repository and access to the repository and does not exist. Whether the registry returns a 404 or a 401 is based on the policies defined in the hub but at least the messaging has been fixed for the user to provide better consistency. Also we are not returning 403 in cases where we should, we should fix that but until then the client is now handling the returned errors correctly regardless of 401 or 403.
