### ISSUE TITLE
Wildcards in scope

### ISSUE THREAD

**Issue by nikolay** [docker/distribution#1308]
I have multiple organizations in my Docker Hub account. How can I create a token that has access only within one organization and for all repos? I tried using just `org-slug` and `org-slug/*`, but neither worked.

**Comment by stevvooe** [comment]
@nikolay The daemon issues a token request for each repository. The authentication layer, registry and the daemon don't have the concept of "organizations". The "organization" concept is enforced in the authentication server and the token will be issued for each individual repository.

This is designed to allow different authentication and access control schemes to be implemented without changing the upstream tools.

**Comment by nikolay** [comment]
I agree, but don't narrow the scope just to my concrete example. I meant something like this: `organization/*`, but in another implementation, it could be: `organization/department/*`, and so on.

**Comment by stevvooe** [comment]
@nikolay I understand. We discussed this heavily during the design phase. The issue here is that we didn't want to have a wildcard protocol that could be an attack vector.

The correct approach is to implement wildcard matches in the token server. For example, if the daemon asks for "library/ubuntu" and the token server allows "library/*", the token server issues a token for "library/ubuntu", since it matches. This way the policy is implemented where the policy is enforced.
