### ISSUE TITLE
Trying to pull : layers from manifest don't match image configuration

### ISSUE THREAD

**Issue by disastrous-charly** [docker/distribution#1439]
Hello,

I have two server, one pulling & running containers, one hosting the private registry, both running debian & docker 1.10
The private registry running 2.3, with TLS and an NFS storage.

When I want to pull I have this issue : "layers from manifest don't match image configuration"

My docker info from the one running containers : 
`Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 132
Server Version: 1.10.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 179
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.29 GiB
Name: worker0
ID: NQKS:BWR4:SQKA:46OP:WZHK:5KNF:CIGX:OPM6:CV3N:QYYM:HNV5:S2WB
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support`

Any clue ?
Should I just remove the /var/lib/docker/aufs/layers/ folder ?

**Comment by disastrous-charly** [comment]
Quick update, I rollback to docker 1.9.1 and registry 2.2, it works.

I think the issue came from the newer registry and not the newer docker-engine.

I let the issue open if you want to discuss it, feel free to close it.

**Comment by aaronlehmann** [comment]
@disastrous-charly: Thanks for bring this to our attention. This looks related to the new content-addressable storage in Docker 1.10. I suspect that the problem is actually happening when the image is pushed - the layers that get pushed to the registry are getting changed in some way from the versions that were originally built or pulled. This is not supposed to happen.

Are you doing anything that might modify the files in `/var/lib/docker/aufs`? I suspect you aren't, but wanted to ask just in case.

Is the image in question one that you're able to share with me? It would be extremely helpful to see:

1. A tar of `/var/lib/docker` from the 1.10 installation that does the push
2. The associated layer blobs from the registry filesystem (these are referenced in `docker/registry/v2/repositories/<repository>/layers`, and live in `docker/registry/v2/blobs/`)
3. Logs from the push and pull process

If this is an image that you can't share, I'd really appreciate if you could try to reproduce the problem with a public image such as `ubuntu`.

**Comment by disastrous-charly** [comment]
Hello ! 
Thanks for your answer.
Unfortunately, as I said, for the moment I came back to docker 1.9 and registry 2.2

But I will try to reproduce the bug later, in a sandbox environment, so we can work on it. 
I wasn't modifying the `/var/lib/docker/aufs`  

What you're saying make me think that I had a strange issue : 
Upgraded servers to 1.10 & registry 2.3 
I wanted to push an image from server1 that already exist on the registry on server2
New layer (427 mo) appears, layer couldn't be pushed, docker retrying several times, got "unexpected EOF" and couldn't push the image.
So I deleted the image and re-pulled it.

It seems related to your idea.

Sorry I can't help more for the moment.

**Comment by naag** [comment]
We experienced the same issue, seemingly after upgrading to Registry 2.3, but it went unnoticed for some time. What fixed it for us was deleting the affected images from the registry using https://github.com/burnettk/delete-docker-registry-image like this:

```
sudo REGISTRY_DATA_DIR=/var/lib/registry/docker/registry/v2 /usr/local/bin/delete_docker_registry_image -i IMAGE_TO_DELETE -v
```

When we upgraded to 2.3, we purged all our images on the registry server and repushed them from our CI server. Maybe the corruption happened during that phase, but unfortunately we no longer know which exact Docker versions were in use during that time.

**Comment by Exordian** [comment]
We experienced the same issue:
Docker version that pushes: 1.10.3 (using overlayfs)
Docker version that tries to pull the image: 1.11.1 (using aufs)
Registry version: 2.4

I can not share the whole image but I can share the Dockerfile build line that builds the layer which might break the thing:
`RUN wget -qO- http://download.jetbrains.com/teamcity/TeamCity-$TC_VERSION.tar.gz | tar xz -C /opt && chown teamcity:teamcity -R /opt/*`
also the issue only happens on TC_VERSION 9.1.7, not on 9.1.6, but that could be a cache problem aswell.

Additional Information:
We tried to fix it, using `docker rmi $(docker images -q --filter "dangling=true")` on the Docker machine that pulls the image (and it deletes orphan layers). Deleted the Image from the registry 2.4, run GC on the registry, build and pushed the image again. Same issue.
Logs:
`Mai 07 21:49:16 www docker[692]: time="2016-05-07T21:49:16.202987899+02:00" level=error msg="Attempting next endpoint for pull after error: layers from manifest don't match image configuration"
Mai 07 21:49:16 www docker[692]: time="2016-05-07T21:49:16.202943534+02:00" level=error msg="Error trying v2 registry: layers from manifest don't match image configuration"` 
I just recognized we did not cleaned / deleted the cache/image on the Docker machine that pushes the image, I'll try that as well in the next days.

**Comment by antoineco** [comment]
Same issue here, _registry_ v2.4.1 serves image pushed by _Docker_ v1.11.2 (CI system).

Older Docker clients (v1.8) can perfectly pull the images, but newer clients (v1.11.2) not.

```
[...]
6914c71be7b3: Pull complete 
94c6cadcdd7c: Pull complete 
layers from manifest don't match image configuration
```

**Comment by Vad1mo** [comment]
Same here with docker hub! since today

**Comment by pmead** [comment]
Same here with Docker Hub since yesterday evening.

This is really breaking our continuous delivery system and because its not a privately owned registry I can't see inside and fix it.

Tarring the image on the build machine and transferring it via SCP to the target works, so its either an issue with the push or the registry, at a guess.

**Comment by alexamirante** [comment]
Having the same issue here with an image built with docker 1.10.3 an pushed to a private registry:2. 

I'm not sure how to retrieve the actual version of the registry image. This is the output of `docker inspect`:
[https://gist.github.com/alexamirante/9d01ba631bdcd54d0ad103ffd789baa0](url)

Pull fails with docker v1.11.1 and v1.11.2, while succeeds with an older version (v.1.8.2).

**Comment by antoineco** [comment]
@alexamirante what FROM image are you using? The problem occurs when you have mixed manifest versions, so if your own image is not the culprit, then your base image (or its own base image) is.

**Comment by alexamirante** [comment]
I'm using the latest ubuntu:14.04. I built the image by passing the `--pull` option to `docker build`.

**Comment by antoineco** [comment]
In that case you have to remove all the layers from the Ubuntu image from your private registry. If they already exist there Docker won't update them (notified by the message "Layer already exists" during a push)

**Comment by alexamirante** [comment]
Any easy way to do that? Thanks!

**Comment by mkonakan** [comment]
@alexamirante : You must try this https://techoverflow.net/blog/2013/10/22/docker-remove-all-images-and-containers/

**Comment by alexamirante** [comment]
@mkonakan that would delete images you have stored locally. IIUC, I need to delete layers from a private registry instead.

**Comment by mkonakan** [comment]
@alexamirante I am sorry. I did not observe the word "private registry" in your statement. I am not sure about the direct way but I am sure you know that you can jump/exec/attach to private registry and see the manifest and delete the "data" folders in each layer basing on the manifest.

**Comment by alexamirante** [comment]
I managed to get around this issue in the following way:

1. start a new private registry
2. push the image from machine A to the new registry
3. pull the image from another machine B
4. push the image on the old registry from machine B
5. destroy the new registry

Now the image can be pulled from anywhere.

I know it's tricky, but I didn't find any smarter way.

**Comment by antoineco** [comment]
You probably want to use the API instead, and delete each faulty image individually. See [Deleting an image](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image) and [this comment](https://github.com/docker/docker-registry/issues/988#issuecomment-175373741)

Example:

Set `REGISTRY_STORAGE_DELETE_ENABLED = true` on your registry, or this:
```yaml
storage:
    delete:
        enabled: true
```

Get available tags for repo 'debian':
```shell
# curl -X GET -u <username:password> https://my.repo/v2/debian/tags/list -u <username:password>

{"name":"debian","tags":["19","26","29","20","22","21","27","latest","25","28"]}
```

Get digest for image 'debian:19':
```shell
# curl -X GET -i -u <username:password> https://my.repo/v2/debian/manifests/19

HTTP/1.1 200 OK
Docker-Content-Digest: sha256:sdvdssa6ada96f8a6f6a8dfa6f6asd786f8dsa6f6as7d6fadsfdsafdsaf
[...]
```

Delete image 'debian:19':
```shell
# curl -X DELETE -i -u <username:password> https://my.repo/v2/debian/manifests/sha256:c66c2d3862d514797085ba4efee2a4b31bca8bbb564fe444c225b509ba4cf582 

HTTP/1.1 200 OK
[...]
```

Run garbage collection:
```
$ docker exec -it your_registry_container \
    bin/registry garbage-collect --dry-run /etc/docker/registry/config.yml
```

**Comment by alexamirante** [comment]
@antoineco I tried that with no luck. I guess the layer which is causing troubles is shared with other images, so it doesn't get deleted when I delete the image. And I don't want to delete all images from registry!

**Comment by antoineco** [comment]
You might have to delete all image from one *repository* (as opposed to the whole registry) I'm afraid.

**Comment by alexamirante** [comment]
Well, my solution, while tricky, does allow you to keep other images...

**Comment by antoineco** [comment]
Right, not sure why it works though, could you update your comment with the client version you used on each machine? ('A', 'B')

**Comment by alexamirante** [comment]
Done.

**Comment by dustinmoris** [comment]
I had the same issue with Docker hub and after reading all the comments this fixed it for me:
- First I deleted the corrupted image on Docker Hub
- Then I SSH'd into my CI machine and deleted all old images there.
- Kicked off a new build and push and then it worked again

**Comment by maxpowa** [comment]
Running into this same problem with https://hub.docker.com/r/maxpowa/npomf/ . The same pull is working correctly on another server running `Docker version 1.9.1-cs2, build 4ade326`.

```
$ docker version
Alias tip: d version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:25:18 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:25:18 2016
 OS/Arch:      linux/amd64

$ docker pull maxpowa/npomf:latest
Alias tip: d pull maxpowa/npomf:latest
latest: Pulling from maxpowa/npomf
674ded4e0a75: Already exists
a3ed95caeb02: Already exists
3fe37ed373c9: Already exists
ddf1745d8563: Already exists
b9ef83e0e547: Already exists
dd3aa96c04c5: Already exists
3daa46d253bf: Already exists
2a194524d7f1: Already exists
245cdac416d1: Pull complete
19e0f1ac8db8: Pull complete
a8d947255fdc: Pull complete
layers from manifest don't match image configuration
```

cc @RX14

**Comment by ntquyen** [comment]
@aaronlehmann  I got the same issue after upgrading to CoreOS 1068.8.0 today with docker 1.10.3. The issue only happens to a few images from private docker hub (automated build images).

**Comment by tomfotherby** [comment]
Today I just got this issue on CoreOS 1068.6.0 and 1010.6.0 (`docker 1.10.3`) - `docker pull` gives `layers from manifest don't match image configuration`. On CoreOS 899.17.0 (`docker 1.9.1`) the pull was fine.

**Comment by ntquyen** [comment]
I realized there's a lot of `<none>` images in `docker images`, may be it's caused by my clean-up scripts to delete unused images. I deleted all those images and got the problem solved.

**Comment by Exordian** [comment]
FYI I've never used cleanup scripts (or other external tools) getting those errors

**Comment by podarok** [comment]
initial docker install
```
vagrant@precise64:~$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

```

result

```
vagrant@precise64:~$ docker run cibox/mysql
Unable to find image 'cibox/mysql:latest' locally
latest: Pulling from cibox/mysql
96c6a1f3c3b0: Pull complete 
ed40d4bcb313: Pull complete 
b171f9dbc13b: Pull complete 
ccfc4df4fbba: Pull complete 
a3ed95caeb02: Pull complete 
4567ed4ddf19: Pull complete 
d9e5c4a18b98: Pull complete 
5fbeff15eff0: Pull complete 
docker: layers from manifest don't match image configuration.
See 'docker run --help'.
```

With downgrading to 1.9.xx all works fine
Ubuntu 14.04 LTS

**Comment by disastrous-charly** [comment]
Hi, 
So can we come with a solution, even dirty ? 
What I will try : 
1) Pull all the registry images & tag from registry on a client (in 1.9)
2) delete the registry container and NFS content on the disk
3) update clients and server to 1.1X
4) start new registry
5) gotta push them all !

What do you think ?

**Comment by devzsolt** [comment]
Hi,

Please let us know if there is a working solution because this bug severely affects our deployment pipeline and removing docker from our build and deployment system would take quite long time.

Thanks a lot

**Comment by dmcgowan** [comment]
@devzsolt are you experiencing this pulling an image you pushed or another hub image (such as `cibox/mysql`). Can you also send your `docker info` output.

**Comment by aaronlehmann** [comment]
I was able to confirm that the `cibox/mysql` image has this problem. It appears to have a layer that doesn't match the hash given in the `RootFS` section of the image configuration. This is curious because we have code in Docker 1.10.1 and later that should disallow any corrupted layer like this from being pushed in the first place.

It would be very helpful if anyone is able to give steps that create an unpullable image with a fresh Docker installation (for example, pull image x, build image y on top of it using the provided Dockerfile, push that, then it can't be pulled by others).

**Comment by maxpowa** [comment]
@aaronlehmann Docker hub's automated build occasionally creates these unpullable images. (See `maxpowa/npomf`, the latest is unpullable by docker 1.10.0)

**Comment by aaronlehmann** [comment]
@maxpowa: I was able to pull the `maxpowa/npomf` image without any issues. Is the current revision still unpullable, or is this something that showed up in the past? If you're still having problems with it, what Docker version are you using to pull it?

**Comment by RX14** [comment]
@aaronlehmann I'm using docker `1.10.0` and pulling `maxpowa/npomf:latest` fails.

**Comment by aaronlehmann** [comment]
It is working for me in Docker 1.12.0 and 1.10.0.

@RX14: When you pulled it, did it download all of the layers, or did some already exist on your system?

**Comment by RX14** [comment]
@aaronlehmann some already existed, which i can't delete cause they are being used by the previous generation of the container and I want a minimal-downtime upgrade.

**Comment by aaronlehmann** [comment]
The existing layers may be an important piece of the puzzle. I think what's happening is that one of the existing layers was downloaded by an older version of Docker that did not save tar-split metadata. The migration to content-addressability computed an ID for the layer, but this doesn't match the ID that comes directly from the tar. The migration also prepopulated the mapping between the layer digest and the artifact digest in `/var/lib/docker/image/*/distribution`. Pulling another image that uses the affected layer will try to use this layer digest from the migration, but that digest turns out to be wrong, so the pull fails.

If this is correct, deleting `/var/lib/docker/image/*/distribution` should fix your problem pulling `maxpowa/npomf:latest`. This is just a cache, so it should be safe to remove (removing it will just cause extra data to be transfered during pushes and pulls until the cache is repopulated).

The `cibox/mysql` issue is not quite the same, but could be related. That is a corrupted image on the registry, so anyone who tries to pull it will have problems, regardless of their local layers. Even with the safeguards we introduced in Docker 1.10.1, if the layer involved is not actually pushed up to the registry, the image config could contain the faulty layer ID from the migration process.

cc @tonistiigi

**Comment by devzsolt** [comment]
@dmcgowan we experienced this problem using Docker Hub (private repo). We had more than a year old archive of images, but using the advice of @dustinmoris we deleted all containers and all images from our build machine and started building the docker image from scratch and it works well again.
If that helps to find the bug, our oldest images were 15 months old but I think the oldest we actually used as a base was just 11 months old.
I hope you can find the cause, until then it's a good workaround to delete the old layers.

**Comment by arabold** [comment]
@devzsolt @dmcgowan We had the same problem with our private repo on Docker Hub. It is more than a year old. Through googling for the "layers from manifest don't match image configuration" error I found this post. The workaround does indeed work. But instead of deleting old layers I've simply created a new repo from scratch - now pulling seems to work fine again.

**Comment by disastrous-charly** [comment]
Hi there, 
It looks like it's working :-)

What I did : 
- Pull all the docker images from private registry to a server, just in case it all goes bananas. (easy to do with a script if you keep names & tags in a database)
- stop and delete the registry container in 2.3 (not the content on NFS)
- upgrade the server which host the registry to docker 1.12 (yolo right ?) (I tried in dev with docker 1.11)
- upgrade the registry to 2.5 with the same folder mount to save the registry content as before
- upgrade the registry clients to docker 1.12 (it was really looooong, because it's analyzing all the docker layers)
- and that's it, it's working, no problem to push and pull. Didn't even have to docker login on the registry.

Thinks to backup your docker.service (/lib/systemd/system/docker.service) before upgrading, if you custom it.

After upgrading docker, try to restart. It wasn't working for me. If it's the case, remove the file : 
/var/lib/docker/network/files/local-kv.db

So far I didn't notice any issue. I will update in one week, just to be sure we are finally done with this issue.

**Comment by disastrous-charly** [comment]
Hey !

So, I still had an issue when trying to push an image. It was because of an old layer which was corrupted I guess, so I got the error : "unexpected EOF" (a classic one :-))

But,
I have finally a simple solution, you don't have to destroy your image !
Just flatten the docker image ! Export to .tar and import, you'll have a new image with only one layer.
You loose the advantage of docker layers but you will not loose data.

You have many tutorials on internet, or you can use : [https://github.com/a-ba/docker-utils(https://github.com/a-ba/docker-utils )

So, the issue is resolve for me.

**Comment by xiemeilong** [comment]
@disastrous-charly  But if you pull the next version ,the same issue would come again

**Comment by zoobab** [comment]
I solved the problem by:

1. deleting the tags of the images that were problematic on the new registry server
2. from a working docker client, pulling the problematic images from a working docker client from the old registry
3. from a working docker client, tagging the pulled images with the tag of the new registry 
4. from a working docker client, pushing to the new registry

Now with a 1.12.1 problematic client, the issue is gone.

**Comment by zoobab** [comment]
There is another solution to the problem of "layers from manifest don't match image configuration" seen on a 1.10 client:

On a docker 1.9.1 client:

$ docker pull myregisrtry.com/myimage:latest
$ docker run --rm -v /var/lib/docker:/var/lib/docker docker/v1.10-migrator
$ docker push --disable-content-trust=true myregisrtry.com/myimage:latest

On docker 1.10 client, the pull now works!

**Comment by dohnto** [comment]
We see this repeatedly on our docker registry `2.4.1`, it disables to do Continuous Deployment. Is this possible to solve this systematically or just use hacks?

**Comment by aaronlehmann** [comment]
@dohnto, did you try deleting the `/var/lib/docker/image/*/distribution` directory as suggested above?

There are a few different scenarios that can cause this. Some involve local metadata that was improperly generated during an upgrade, and in this case, clearing that directory should solve the problem. In other cases, an image on a registry may be corrupted due to a few bugs that existed in older versions of Docker. In these cases it's necessary to re-push the image, and the problem shouldn't reoccur afterwards because the bugs (that we know of) have been fixed.

**Comment by dohnto** [comment]
@aaronlehmann Thank you for your reply. I am unfortunately not the one who has admin access to our registry, just a user of it. Anyway, we use swift storage driver. What to delete in such case?

**Comment by bwesen** [comment]
Got this problem today, after re-building a container and pushed to our registry. It looked like all layers were pushed fine, but the client (on another computer) now gets the dreaded message of layer/configuration mismatch. The building computer was recently upgraded and therefore maybe got a Docker upgrade.

A second client pulls the image just fine (it was clean, so it really pulled all layers), so the layers can't really be corrupted on the registry server (but there might be subtleties in hash interpretations maybe between client versions like this thread suggests? I didn't really understand exactly)

**Is there ANY way to debug this message?** To see exactly what the client expects and where it mismatches? I'm curious, in either case. 

FWIW the **pushing** Docker version was 1.13.1 (but used some previously built layers, probably from a one step older version). The client that **worked** with the pull is 1.6.2, and the client that gave the **error** is 17.12.0-ce (it's from the Amazon distro used on AWS ECS).

I'll do the obvious test with trying to pull from a third client if I can get that 17.12.0 version on it..

**Comment by bwesen** [comment]
I tried the other solution above, managed to rebuild the two dependent base images and re-push them to the registry, and now it works to pull the image again.

I guess there is some bad combination that can happen when a new client tries to pull an image built by a new client based on images built by older dockers :) or something..

**Comment by YenF** [comment]
I am running into this problem even if with the same version on different architecture.
Image pushed from ubuntu14
```
docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:18:46 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:16:59 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

However when I wanna pull the uploaded image from another Debian8 machine it popped out `docker: layers from manifest don't match image configuration.`.
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:16:02 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:14:13 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by heyman** [comment]
I had the same issue with an image built by docker hub when trying to pull it to a server (that has been running older versions of the same image, on multiple different versions of docker, for multiple years). 

@aaronlehmann's solution of removing `/var/lib/docker/image/*/distribution` resolved the issue.

**Comment by bwesen** [comment]
> Got this problem today, after re-building a container and pushed to our registry. It looked like all layers were pushed fine, but the client (on another computer) now gets the dreaded message of layer/configuration mismatch. The building computer was recently upgraded and therefore maybe got a Docker upgrade.

It's the future now, 2023, and I just got this error, 7 years after its first occurrence. It would have been helpful if the error message could have been improved to say exactly what the problem is :)

I rebuilt and pushed an image to our private registry, an image I hadn't built and pushed since 6 years, and now the client (another computer) can't pull it without getting this error message.

FWIW the Dockerfile has a FROM golang:1.4 which I'm sure is an old image, but it's not something I can rebuild or change version of..

Are the only solutions still the filesystem hacks with rm's of files? Or is there a docker command that cleans up everything and refetches everything or what else is needed to fix it?

**Comment by fbruetting** [comment]
Same for me. I re-ran a pipeline which used to run successfully three months ago with exactly the same base image, and now I surprisingly get this error.

**Comment by milosgajdos** [comment]
That seems to be `moby` problem, not a `distribution` problem. Please ask in `moby/moby`

**Comment by alkhachatryan** [comment]
I was installing postgis with docker-compose and got that error. Simple re-run of the command fixed this issue.
