### ISSUE TITLE
Image identity from registry

### ISSUE THREAD

**Issue by jarmoni** [docker/distribution#1442]
Maybe I got something wrong but I always thought that docker follows the approach of an unique artefact which can be stored somewhere (local, registry), deployed everywhere - and one can be sure that it's always the same artefact.

Up to now I found no (convenient) way to compare a local image with an image in a private registry.
We run several systems, each in own network (inhouse and/or "real world") and have a private registry in each of these network-segments. So we have to check differences between images - local and in several private registries as well.

When I execute:

```
docker images --no-trunc
```

I get a checksum in 3rd column. I would expect that the registry-api would allow me to compare local vs. remote image via this checksum. Or in an example: 

* I create (local) limage some_image:1.0.0
* I tag it twice: 169.4.7.36:5000/some_image:1.0.0 and 10.0.0.2:some_image_1.0.0
* I push both
* I alter some_image:1.0.0 local

I would expect to check easily if my modified image differs from the both remote images. But it seems to be the only way to check all layers.

Why is it such difficult to check image-identity?

Or did I miss something?

**Comment by stevvooe** [comment]
@jarmoni Much of the work over the last year has been decoupling the registry and the daemon. Part of this is allowing both entities to identify content in a way that makes most sense to it. For docker itself, it uses a set of verifiable identifiers corresponding to unpacked images and configurations. For the registry, this means images will be identified by their packaged and compressed contents. To keep the registry simple, the engine can keep track of the external image identifies and use that to fetch and distribute them.

The other aspect to the ongoing changes is providing consistent identifiers. In the V1 registry protocol, image ids were random and actually controlled by the registry. If two registries had different identifiers for an image, there was no recourse to address the overlap, opening up serious security issues. There are two approaches to address this. The first is to ensure that identifiers are controlled by a central authority, which has both technical problems and logistical problems when a central authority may not even be desired. The second approach, which we've opted for, is to make the images _content addressable_. This means that no matter what machine you are on, if you have two images with the _exact_ same content, they should have the same identifier.

The main benefit of this approach is to allow image formats and distribution models to evolve separately. We also get more secure distribution through unreliable channels. While these are fairly intangible to users of the software, it will open up longstanding missing features over the next year.

Part of the trade of we made here was image identifier stability. For this to work as you expect, images must have the same _exact_ content. The issue arises with the way docker stores images. When the image is expanded on disk, we actually change the nature of the content (tar -> disk) such that when the contents are repacked, the identifier may change. Arguably, trying to regenerate the exact same content is a broken approach, but we didn't want to change the way the docker engine works to rapidly. This is likely the cause of the behavior you are seeing.

The goal is to balance identifier instability and collisions. We can look at these properties of image identifiers as two ends of continuum. At the instability end, we end up transferring more data than necessary and have no convenience of common identification. Small changes, commonly timestamps, change identifiers needlessly and make them less useful. However, the collision end of this continuum yields massive correctness problems and security issues. Ideally, one wants to identifiers to be stable as possible with having collisions. Collisions are very bad, so we err on sacrificing stability.

That said, the properties covered above are a good thing. The changing identifiers ensure that slight variation is detected. While this can affect usability, it is a vital property of the approach. The solution here is to converge the stability of image identifiers. This can be done by slowly and carefully chipping away at content variation without introducing collisions.

> Why is it such difficult to check image-identity?

I hope the above provides adequate background.

Arguably, the `docker images` command should have some facility for printing out the registries identifier space for an image. It should be clear that this is the fetching identifier.

The other aspect to this problem is having a remote index of image identifiers as seen by the docker daemon. The problem with this is the identifiers used to ensure that remotely fetched content doesn't collide may be different from version to version, since it depends on the implementation. The only key that makes sense to access remote images is the identifier of the packed content.

Since this is more of a daemon UI issue, I am going to go ahead and close this. If you want to be able to have the registry's image identifier in the `docker images` output, please file an issue there.

Sorry for the book.
