### ISSUE TITLE
Separate out docker image build and deployment steps into an independent command line tool

### ISSUE THREAD

**Issue by popoludnica** [docker/distribution#1503]
Container image build and deployment is considered a separate process from container runtime in many enterprise environments.
It would be super-cool (liberating and sensible) if docker image build was independent of docker-engine, docker file-system storage and didn't require any special privileges on a build host. 

It can be solved in a form of a command line tool responsible for the following:

* building new image layers from provided content,
* building new image manifest referencing parent layers and new layers from the step above,
* uploading new layers/blobs to the registry repository,
* mounting or uploading parent layers to the registry repository,
* uploading the new manifest to the registry

Sometimes an example is worth a thousand words:

`imagebuild [PARENT]... [LAYER]... --name=IMAGE`
`   PARENT: <IMAGE>`
`   LAYER: <uri>`
`   IMAGE: <registry>/<reponame>[:<tag>]`

I can arrange for contribution of the code if there's any interest? Proof of concept of the above described tool already exists.

Image build split out mentioned: https://github.com/docker/docker/issues/18596 
Partial overlap of requirements: https://github.com/docker/docker/issues/18585, https://github.com/docker/docker/issues/17982, https://github.com/docker/docker/issues/7115

**Comment by dmp42** [comment]
Thanks @popoludnica 

You are right, and I believe separating "build" from the runtime is something many people want.

Nevertheless, this has (almost) nothing to do with this repo here (which is about the client and server side implementation of the transfer protocol).

I would suggest you open up your suggestion on `docker/docker` for more visibility.

Closing this for bookkeeping since there nothing actionable on the distribution side to do.

Let me know if that helps.

**Comment by popoludnica** [comment]
I assumed that docker/distribution might eventually swallow the build and distribution code and host also related client side tools. That's fine, I'll reopen on the docker/docker side of the fence, thx.
