### ISSUE TITLE
Proposal: remove 'include_gcs' conditional build tag?

### ISSUE THREAD

**Issue by arschles** [docker/distribution#1572]
I noticed that the S3 and Azure don't have conditional build tags, so is it reasonable to remove the one for GCS?

**Comment by dmp42** [comment]
I would rather have more conditional tags than less, so that people who roll their own can disable compilation of drivers they don't want.

That being said, S3 and Azure are well supported / maintained / tested, while at this point GCS is still new (hence the reason why it has a tag and not the others).

**Comment by arschles** [comment]
@dmp42 makes sense - thanks for letting me know! When I first posted, it was causing a minor issue, but we got over it. It's no issue now. Sorry for not responding sooner.
