### ISSUE TITLE
Migrate Registry between server using S3 Backend

### ISSUE THREAD

**Issue by beatscode** [docker/distribution#1726]
If I start a new registry on a new server with the same backend is that the same as migrating a registry? I tried to recreate a working registry on another server but none of my docker pull queries worked. However the s3 bucket seemed in tact. Any suggestions on migrating the metadata

**Comment by dmcgowan** [comment]
@beatscode if you are using the same configuration then there should be no need to do any data migration. The metadata is currently stored inside of the s3 bucket. Check your configuration and if you are still having issues post the debug logs for the registry during a docker pull.

**Comment by beatscode** [comment]
So somehow the bucket was deleted however the registry still operates. Is there anyway to migrate the registry metadata and images to another server or should i just start over?

**Comment by dmcgowan** [comment]
If the bucket is gone you will need to start over. The metadata and image layer data is all stored in S3. In the future, when migrating with S3 you should be able to copy the configuration to the new server, bring up the new registry, test it, then shut down the old one. Since S3 contains all the shared data and it can be accessed by multiple registries simultaneously there is no reason to attempt an offline migration.
