### ISSUE TITLE
Catalog API docs incorrect

### ISSUE THREAD

**Issue by jantman** [docker/distribution#1769]
The [documentation](https://github.com/docker/distribution/blob/master/docs/spec/api.md#get-catalog) for the ``_catalog`` API endpoint states that a request to ``/v2/_catalog`` will return a complete, unabridged list of repositories. However, running the Registry from the 2.4.1 image with Redis and an S3 backend, this endpoint returns exactly 100 results, even though I have 209 repositories.

**Comment by dmcgowan** [comment]
@RichardScothern  Looks like the implementation is capping out at 100 entries when nothing is specified. See https://github.com/docker/distribution/blob/master/registry/handlers/catalog.go#L42.
Should we update the documentation here? I assume the reason is that without having an upper limit the registry would need to loop to get all the entries.

@jantman for now try using the `Link` header which gets returned to continue fetching. You could also specify a larger number to return but given you likely do not know the exact size, paging will likely work out better for you.

**Comment by RichardScothern** [comment]
The use of 'unabridged' is incorrect there and should be removed.

The spec says that the list can be capped by the registry with pagination links returned.
https://github.com/docker/distribution/blob/master/docs/spec/api.md#listing-repositories

**Comment by jantman** [comment]
I got my code working before opening this issue, using the paginated endpoints (when it finally occurred to me to look for the Link header). But I lost a few days of work thinking that my v1-to-v2 migration script was broken, because I was going by https://github.com/docker/distribution/blob/master/docs/spec/api.md#get-catalog which clearly shows two different behaviors, one paginated and one returning the __complete__ result set. IMO, that doc should just be updated to entirely remove the ``Catalog Fetch Complete`` section.
