### ISSUE TITLE
Corrupt repository after delete of manifest

### ISSUE THREAD

**Issue by mhornbech** [docker/distribution#1848]
In order to maintain a stable amount of disk space in our private registry we only wish to keep the most recent manifest for a given tag, and then let garbage collection clean up the rest. We implemented this be deleting the current manifest before pushing a new one. This seems to work fine, except for our Cassandra image which is defined as follows:

FROM cassandra:3.0
MAINTAINER datasolvr

In this case, after deleting the current manifest and pushing a new one, all pull requests return an "Image not found" error. The only way to repair it (that I found) was to build a new registry from scratch. Our workaround is simply not to delete manifests for this image, which isn't necessary anyway, but I report the issue since the state corruption could prove very problematic in some situations.

**Comment by RichardScothern** [comment]
Can you post the steps you are following?  There is nothing special about that image, except that it doesn't have a latest tag.

**Comment by mhornbech** [comment]
I have just verified that the following steps reproduces the error

1. Start a clean registry 
2. Push the image with tag 'master'
3. Fetch the manifest digest and delete the manifest
4. Run garbage collection
5. Push the image with tag 'master' again
6. Pull the image with tag master results in "image datasolvr/cassandra not found"

If I omit step 4 the error goes away. Also step 5 runs in around 1s, with this output

The push refers to a repository [registry.aws.datasolvr.com:5000/datasolvr/cassandra]
69b0ed05611c: Layer already exists 
a3ed72d7c348: Layer already exists 
30fa62369d75: Layer already exists 
f1e9dd6e16ef: Layer already exists 
bd77218e54f2: Layer already exists 
4af6922fc82e: Layer already exists 
d9654c615772: Layer already exists 
328581ff82aa: Layer already exists 
c778f98ec927: Layer already exists 
42755cf4ee95: Layer already exists 
master: digest: sha256:873c4cbd606d02e23c67075af1bcb5630f6b47d275a64014cc1ca8473f8c3f93 size: 2385

So it seems that it doesn't really push anything the second time.

**Comment by mhornbech** [comment]
Registry version 2.4.1 btw

**Comment by RichardScothern** [comment]
Between steps 3 and 4, the registry should be put into read-only mode via a restart (without which garbage collection can not guaranteed to be safe).   This also has the side effect of invalidating any caches used by the registry.  The garbage collection process runs on the storage driver level and unfortunately does not do this.

**Comment by mhornbech** [comment]
Restarting prior to step 4 solves the problem.

What exactly do you mean by "not guaranteed to be safe" - as far as I can read from the documentation it is only a problem if images are pushed while garbage collecting. In our use case (since it is part of a build pipeline) this cannot happen.

**Comment by RichardScothern** [comment]
That is what I meant

**Comment by jjamor** [comment]
I have a similar problem, steps followed:

1. Start a clean registry
2. Push the image with tag 'master'
3. Fetch the manifest digest and delete the manifest
4. docker stop registry
5. Run garbage collection.
6. docker start registry
7. Push the image with tag 'master' again
8. Pull the image with tag master results in "image XXX not found"

I'm not sure if I should remove registry container and recreate it after GC instead of stopping and starting the same container.

Thanks!

**Comment by mhornbech** [comment]
The only thing I did different was switching your steps 5 and 6. Maybe the cache invalidation doesn't happen until startup - that could explain it.

**Comment by diamantn** [comment]
Seeing a similar issue. It seems the deletion / garbage collection features are not working. Distribution version is v2.5.0
As a side note, the API does not support deletion of tags...

**Comment by mhornbech** [comment]
While not optimal, using the steps I outlined above we have, through the current API, been able to maintain a stable level of disk space on the registry server which is part of our automated build pipeline - that is images are pushed 5+ times a day. Before pushing we delete each image like this

REGISTRY=$1
IMAGE=$2
TAG=$3

HEADER=$(curl -I -H "Accept: application/vnd.docker.distribution.manifest.v2+json" http://$REGISTRY/v2/$IMAGE/manifests/$TAG | grep "Docker-Content-Digest")
DIGEST=${HEADER#Docker-Content-Digest: }

URL=http://$REGISTRY/v2/$IMAGE/manifests/$DIGEST
curl -I -X DELETE -H "Accept: application/vnd.docker.distribution.manifest.v2+json" ${URL%?}

Then run a restart + gc over ssh, and finally push the new images.

**Comment by diamantn** [comment]
@mhornbech This is interesting. However, I just tested:
1. Starting a clean Registry
2. Deleting a manifest via  curl.
3. Running GC and restarting the registry. (tried GC and restart and the other way around)
4. Listing tags, the Registry returns the ostensibly "deleted" tag for the "deleted" manifest.
:(
Could anyone verify?

**Comment by mhornbech** [comment]
It won't delete the tag, but it deletes the image associated with the tag. You can see it if you look a bit into the registry's underlying file structure. So basically you can end up with a tag without an image, which will provoke an 'image not found' error upon pull. Also it will only delete the newest image for that tag - as far as I can see there is absolutely no way to obtain the digest of images prior to the latest. The method I mention above works because we delete the latest image prior to every push.

**Comment by mhornbech** [comment]
I will close this issue since the original problem has been solved, but feel free to keep commenting.

**Comment by monikakatiyar16** [comment]
Do we store the manifest info in cache - the one which we get on hitting the curl command for manifest
curl -k -v --silent -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET https://privateregistry:port/v2/imagename/manifests/tag ?

For a scenario where the push will not happen at the same time when garbage collection is being executed, I am able to delete the layer completely without restarting the container as follows : 

1. Delete the manifest (Doesn't delete the actual  blobs, but untags the image - making it unavailable by deleting the link files from current and revision folders from mounted volume). Getting the Manifest sha id using the Docker-Content-Digest sha value : 
curl -k -v --silent -X DELETE https://privateregistry:port/v2/imagename/manifests/sha-id
2. Delete all the blob layers (Deletes the data file in the _manifest/layers, actual blob remains intact). Getting the Blob sha from layers {} values from the json
curl -k -v --silent -X DELETE  https://privateregistry:port/v2/imagename/blobs/sha-id
3. Run GC (which actually hard deletes the unreferenced blobs)
docker exec -it jisto_registry bin/registry garbage-collect /etc/docker/registry/config.yml
If the image is referenced by other image, gc deletes all the references but keeps the layer that contains the actual blob referenced by other image intact. The dependent image contains a reference to this layer in the manifest / layers folder, due to which maybe gc doesn't sweep it.

When I push the same image again, everything works fine as of now, except getting the manifest. It throws manifest_unknown error. Studying the underlying folder structure, found that in blobs folder one of the layers contain the manifest information, which is missing at the second time I pushed the image.
However restarting the container does create this file. 

After gc why can't we have the push recreate the folder in blobs/ containing the manifest information if it doesn't find one from cache on re-pushing image after delete process done above.

I have read the consequences of possible data loss that can incur if someone pushes same or the dependent image while the gc is running. In my case, such scenario will not happen. Without restarting the container, I find this manifest file creation issue only at this point of time. Any suggestions on this how are we maintaining this in cache?
