### ISSUE TITLE
can registry proxy pushing operation to center registry?

### ISSUE THREAD

**Issue by elianka** [docker/distribution#1849]
I know that now registry has the pull through cache feature(proxy), and when we configure proxy function on a registry, it cannot be pushed anymore. 
so can we use the registry as a proxy to redirect "PUT" "POST" "DELETE" requests to the center registry which we had configured?

**Comment by dmcgowan** [comment]
Short answer to this is no. The proxy cache/mirror feature is not intended to allow proxying pushing to another registry. We may consider features where only certain images in a registry may be mirrored. One of the reasons we want this separate is so that a mirror does need to be given push authorization, then we can reduce the amount of trust needed for mirrors.
