### ISSUE TITLE
Support for running with ECS Roles (bump AWS SDK to 1.2.5+)

### ISSUE THREAD

**Issue by xose** [docker/distribution#1937]
I'm deploying a private registry on ECS and would like to use IAM Roles for the task so the access keys for S3 get assigned and rotated automatically.

This feature requires the AWS Go SDK 1.2.5, but the registry currently depends on 1.2.4. No code changes are required.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Comment by robbeblock** [comment]
Any updates on this?

**Comment by dmcgowan** [comment]
Pushing this out to 2.7, please consider opening up a PR to update library.

**Comment by dmcgowan** [comment]
SDK has been updated and will go out with 2.7

**Comment by galindro** [comment]
@dmcgowan when 2.7 will be available to pull? Is there an ETA?

**Comment by dmcgowan** [comment]
@galindro The plan is within the next month. Until then you can run a build from master with `distribution/registry:master`, our master should be fairly stable since we are not merging in any large features before the release. Suggestion if you go this route, find a build which you validated as stable and push it to your own repository so you can pin the tag or run by digest.
