### ISSUE TITLE
It is too slow to get /v2/_catalog result !!!

### ISSUE THREAD

**Issue by duyanghao** [docker/distribution#1963]
Registry v2(2.5.1) with s3 backend:
when i execute `curl http://xxx/v2/_catalog`,it will get response after 10s as below:
start time: `Sun Sep 18 17:19:44 CST 2016`
end time: `Sun Sep 18 17:19:55 CST 2016`
But it is too slow to get `/v2/_catalog` response!!!
i look over the catalog source code and find that it will execute `Walk`, i guess `Walk` function is too time-consuming.
So,why not store image name into SQLite database as registry v1 does? that will save a lot of time!!!

**Comment by ahmetalpbalkan** [comment]
@duyanghao I believe storing image names in a local sqlite file would violate the fact that registry v2 is stateless and can scale horizontally easily.

**Comment by RichardScothern** [comment]
@ahmetalpbalkan @duyanghao while this is true there are compelling reasons for storing metadata in a third party data store and that is the direction we will take with the registry.

Unfortunately we are a bit resource constrained at the minute but there is a proof of concept [here](https://github.com/RichardScothern/distribution/pull/1) which I intend to complete.

**Comment by m-masataka** [comment]
@RichardScothern I think your proof of concept is great.I think registry should have metadata too.
But why this implementation has stoped at  Nov 2016?
Does anyone continue to implement this function?

**Comment by AkihiroSuda** [comment]
@RichardScothern @stevvooe @dmcgowan
What's current status?

**Comment by stevvooe** [comment]
@AkihiroSuda The performance here is mostly due to the abhorrent round trip times in s3. Other drivers, such as the filesystem driver, that aren't so slow to provide metadata perform much better. Performant applications should really be using the notification API to sync data out.

To address this problem, we'd have to add another component to store metadata in a better performing storage, which would complicate deployment for a system that is really designed to serve up content. In practice, the catalog API is more for syncing.

I'm going to close this in favor of the more politely worded #947. :smiley_cat:
