### ISSUE TITLE
remove the http.secret parameter or demonstrate a need for it

### ISSUE THREAD

**Issue by vikstrous** [docker/distribution#2012]
As noted in https://github.com/docker/distribution/issues/1599, there doesn't seem to be any attack that the secret actually prevents. If that is the case, I don't think the secret parameter should exist. If there is an attack that it actually prevents, it should be made clear what it is so that people actually use this parameter correctly. Otherwise, everyone will just hardcode a placeholder.

**Comment by stevvooe** [comment]
The http secret secures the upload state from client and upstream storage backend. The hmac secret prevents tampering from the client, since data is passed backed through URL, and inconsistencies in the backend.

It is a component of a layered security defense. If other components are compromised, such as client authentication or parts of the storage driver, it provides extra defense against extraneous or cross-repository writes. Compromise could include active exploits that we don't have knowledge of or future bugs. This provides a layer of protection preventing a leaked upload URL from providing unfettered write access to the backend.

In addition to the above, it also provides a mechanism to store state between registry instances without have to share a common database. Compromising this guarantee prevents future additions to uploads that may require a database for running this registry. Not having an HMAC would be the same as having all registry instances world wide connect to the same database backend.

In common deployments, this is not a concern, as the registry will generate a secret automatically. For high availability deployments or deployments that require write or read scaling, instances will have to share a common secret.

cc @diogomonica @NathanMcCauley

**Comment by vikstrous** [comment]
Please provide an example of something the client can do if they know the secret that they can't do if they don't know the secret. Modifying temporary state is not an attack.

**Comment by dmp42** [comment]
> Modifying temporary state is not an attack.

Sure. It's just one loose end that you would leverage as part of an attack.

Do you agree, for example, that the ability to race out / write random stuff in `/tmp` on a linux system, while not an attack in itself, is certainly a dangerous thing?

**Comment by vikstrous** [comment]
This makes sense. I still wish there was a known attack, but now I understand the role of the signing. This removes the need for the registry to guarantee that modifications to the state by the user are safe regardless of whether or not they currently are. It reduces the attack surface.
