### ISSUE TITLE
How to get total size of a docker image by docker registry API properly?

### ISSUE THREAD

**Issue by ScorpioCPH** [docker/distribution#2034]
I want to get total size of a docker image by docker API, such as `GET /v2/<name>/manifests/<reference>` which is described here [docker spec][1]

I got a list of layers with size, such as this [example](2), I add up these sizes but got a number which is smaller than `docker images` command show, as i know the docker registry stores these layers files as gzipped tar files, so this sum should be smaller than the size which is showed by `docker images` command.

How to get the total image size properly by docker registry API properly? I want to get the same size as `docker images` command show.

  [1]: https://docs.docker.com/registry/spec/api/#pulling-an-image-manifest
  [2]: https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 149
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 154
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: 7PG6:4KEH:35PT:ZZHF:UK2L:SJHJ:HKHT:YX7Q:X2EA:FVSE:GTUG:FEFF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 60
 Goroutines: 85
 System Time: 2016-11-02T11:31:18.840580505Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

```
$ docker exec -it 70bac02fe035 registry --version
registry github.com/docker/distribution v2.5.0
```

**Comment by RichardScothern** [comment]
I'm afraid this is not possible.  As you concluded the registry stores layers as gzipped tars while the docker engine does not.

**Comment by ScorpioCPH** [comment]
@RichardScothern, ok, is there any plan to return this parameters in docker API?

**Comment by dmcgowan** [comment]
@ScorpioCPH the distribution API will not return any additional information about the image. All information about the image should be found in the configuration referenced by the manifest. Currently the size is getting excluded from the configuration, see https://github.com/docker/docker/blob/master/image/image.go. This could be because the size can be misleading, there is on disk size, push/pull payload size, and sum of ungzipped tars. The size of the ungzipped tars is often used to represent the size of the image in Docker but the actual size on disk is dependent on the graph driver. From the registry perspective, the sum of the gzipped layers is most important because it represent what the registry is storing and what needs to be transferred.

I would suggest adding an issue in docker to include the sum of the uncompressed tars in the image configuration. This value should no longer change as of the updates for 1.10 and could be safe for inclusion. The size would also need to be documented as to what is represented, so not to be confused with on disk size. Going to close this issue here.

**Comment by crizCraig** [comment]
Looks like it can be obtained via the tags API resource nowadays

https://cloud.docker.com/v2/repositories/deepdriveio/deepdrive/tags/?page_size=25.&page=1

**Comment by bcspragu** [comment]
> Looks like it can be obtained via the tags API resource nowadays under `full_size` and `size`
> 
> https://cloud.docker.com/v2/repositories/deepdriveio/deepdrive/tags/?page_size=25&page=1

I know this is a three (almost four!) year old bug, but it appears the `/v2/repositories/<name>/tags` endpoint is available on Docker's registry, but not on a self-hosted private registry based on this project. For example, I don't see an equivalent `/v2/repositories/...` endpoint [in the code](https://github.com/distribution/distribution/blob/52d948a9f51c953b646f02cfaa9b9d95e1ad5f3c/registry/api/v2/descriptors.go) or in [the API specification](https://docs.docker.com/registry/spec/api/).

Is this functionality something Docker-specific and proprietary, or is there a way to get this functionality on a self-hosted/private repository?

**Comment by milosgajdos** [comment]
> Is this functionality something Docker-specific and proprietary

This is correct - Docker offers `/v2/repositories` endpoint as part of their Hub API offering. Registry i.e. `distribution` project provides `/v2/<name>/tags/list` API endpoint that's part of [`distrubution-spec`](https://github.com/opencontainers/distribution-spec/blob/v1.0/spec.md#endpoints), though.
