### ISSUE TITLE
Method GET may lead data leaking

### ISSUE THREAD

**Issue by HuKeping** [docker/distribution#2082]
https://github.com/docker/distribution/blob/master/registry/client/auth/session.go#L370

At present distribution uses `GET` to fetch the JWT with an base64 encoded `username/password`, will this put user's credential on risk?

**Comment by dmcgowan** [comment]
Having the credentials in a header or query parameter don't make any difference for security in this case. The convention of not putting in the query string however is very important for browser based interactions, which this request should not be. That being said, we did add support for refresh tokens which are passed along via a post body and support in the specification for passing the credentials in a post to be compliant with the OAuth2 RFC. However since older docker engines were already using GET for credentials, we only use the POST request with the newer refresh token feature.

My opinion is that this does not automatically add risk to the users credentials. Token server operators should take care when using SSL terminated reverse proxies to either not output the credentials in the query string or add support for refresh tokens to completely avoid this issue. Your concern is valid and I would encourage using refresh tokens over passing credentials.

**Comment by stevvooe** [comment]
@dmcgowan Using `GET` here is a legacy thing. Do we support `POST` of this, as well?

Either way, this isn't an issue if you're using TLS.

**Comment by dmcgowan** [comment]
Yes, `POST` is supported in the protocol and on the Hub. However it is not used with the Hub today because they have not added support for refresh tokens.

**Comment by stevvooe** [comment]
Closing this issue.

Please use TLS with the token server to avoid leaking of user credentials.
