### ISSUE TITLE
client always uploads the layer image even if the layer image (blob with the SHA) exists

### ISSUE THREAD

**Issue by yuwaMSFT2** [docker/distribution#2136]
Noticed that when push a new repository to the registry, even if a referenced layer image exists, client always upload. Only in the final commit, the registry will check if the SHA layer image exists or not; if yes, it skips copying the upload over to final blob location.

In such case, client only needs to add the link file to the real layer image, but does not need to upload the image itself at all. Is it possible to do so?

**Comment by aaronlehmann** [comment]
This is possible using a cross-repository blob mount: https://github.com/docker/distribution/blob/master/docs/spec/api.md#cross-repository-blob-mount

Docker has supported this since 1.10, so generally recent versions of Docker (when paired with a recent enough version of the registry) won't have to upload layers that already exist on the registry.

**Comment by yuwaMSFT2** [comment]
@aaronlehmann Thank you! Will take a look at the cross-repository mount.
