### ISSUE TITLE
Fedora 25 crashed (not due to Docker) while running "docker start container_name" and the Port remained occupied

### ISSUE THREAD

**Issue by Spooky-0** [docker/distribution#2255]
I have a docker container (Postgres) which maps a local port to a docker port via 

docker run -e POSTGRES_PASSWORD=mysecretpassword -e PGDATA=/var/lib/postgresql/data/pgdata -v /home/ysaive/go/src/scrape/pgdata:/var/lib/postgresql/data/pgdata:Z -p 5432:5432 -d postgres

After restarting my computer I needed to first start the docker deamon (service docker start) and then start the container (docker start container_name). While doing this my computer crashed for unrelated reasons.

After booting up again I tried the same thing again, with docker start container_name giving the following:
Error response from daemon: driver failed programming external connectivity on endpoint dreamy_shaw (0652adb84f10d9e880090056061a684b7b6273ecc33017207b5f5b58760db04d): Bind for 0.0.0.0:5432 failed: port is already allocated

I removed the container and made it again with (as above)
docker run -e POSTGRES_PASSWORD=mysecretpassword -e PGDATA=/var/lib/postgresql/data/pgdata -v /home/ysaive/go/src/scrape/pgdata:/var/lib/postgresql/data/pgdata:Z -p 5432:5432 -d postgres

but got the same error message:
52068bea013781760ed9b1d26b92ab33d95baeea7c6f8270e0555440b00e2c15
/usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint amazing_goldstine (45d8b02b610e5c11bcc005615887a63c85bf81fdcde1f8459bf5622d9640109c): Bind for 0.0.0.0:5432 failed: port is already allocated.

I resolved the problem as follows:
sudo netstat -tulnap | grep '5432'
-> tcp6       0      0 :::5432                 :::*                    LISTEN      2726/docker-proxy-c 
which gave me the PID of the process which blocked the port, and then
sudo kill 2726

After this I still could not create the container again, I first needed to stop and start the docker service again.

**Comment by dmcgowan** [comment]
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not the place to submit bug reports for the engine, if it is determined to be a bug then file an issue with the docker engine.
