### ISSUE TITLE
Use OSVersion when resolving manifest list entries

### ISSUE THREAD

**Issue by friism** [docker/distribution#2398]
`OSVersion` is used on Windows do discriminate between images for different "builds" of Windows. There's a new Windows Server build in the pipe for the first time since container support was added, so we need this.

Glancing at the code, it looks like `OSVersion` is not used to resolve manifest list entries:
https://github.com/docker/distribution/search?utf8=%E2%9C%93&q=OSVersion+&type=

**Comment by tianon** [comment]
https://github.com/moby/moby/issues/34875 is a related issue (regarding `variant` on `arm` images).

**Comment by tianon** [comment]
https://github.com/moby/moby/pull/34924#pullrequestreview-65345302 is also probably of interest

**Comment by stevvooe** [comment]
This field was deprecated.

**Comment by dmcgowan** [comment]
@stevvooe deprecated in favor of the new platform specifiers? What would replace use of `os.version` in the OCI platform field?

**Comment by stevvooe** [comment]
@dmcgowan Actually, it was left in place, apologies for the confusion.

The issue I see is that it is under-specified. What lands in that field? Do versions have an ordering? What is implied by that ordering? It would be good to have the microsoft folks work with OCI to define what is actually needed here, rather than have us guess.

**Comment by friism** [comment]
Closing, this was addressed in Moby
