### ISSUE TITLE
vendor: replace rsc.io/letsencrypt with golang.org/x/crypto/acme/autocert

### ISSUE THREAD

**Issue by nim-nim** [docker/distribution#2497]
The  rsc.io/letsencrypt vendoring is an obsolete and unsupported commit

Please update to stable release  v0.0.1 which has not seen changes for months

**Comment by dmcgowan** [comment]
We are looking for a contribution to move off this library to https://godoc.org/golang.org/x/crypto/acme/autocert

**Comment by fixl** [comment]
I've had a go at this and got it to work, but since https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811 happened, we have to also listen on port 80 to get through the `http-01` challenge (See: https://godoc.org/golang.org/x/crypto/acme/autocert#Manager.HTTPHandler).

Not quite sure if there is any way around this until the LE folks come up with a better TLS-SNI challenge solution.

Any recommendations are welcome, and I can put a PR through once I'm happy with my work.

**Comment by elboulangero** [comment]
Apparently the PR #2530 was merged instead of this one, if I'm not mistaken. Maybe this PR is obsolete? Can it be closed to avoid confusion?

**Comment by thaJeztah** [comment]
Yes, this should be fixed on master through https://github.com/docker/distribution/pull/2926

Also relates to https://github.com/docker/distribution/issues/1976, which looks to be tracking this for 2.7.x (not sure if that should be tracking it for 2.8.x instead?)
