### ISSUE TITLE
Is the release process gone?

### ISSUE THREAD

**Issue by mauri** [docker/distribution#2503]
Haven't seen a release in a while. Are they officially abandoned?

**Comment by tamird** [comment]
In particular, current versions of https://github.com/moby/moby depend on at least https://github.com/docker/distribution/commit/429c75f and https://github.com/docker/distribution/commit/2caeb61 so it isn't possible to use the docker API client without forcing an unreleased version of this project.

**Comment by stevvooe** [comment]
> Haven't seen a release in a while. Are they officially abandoned?

No, the project is not abandoned. We are working towards moving the specification into OCI (see https://github.com/opencontainers/tob/pull/35). We'll mark a release when that process is complete or maybe before, but we are mostly in a maintenance phase, as the API has been stable for some time.

> use the docker API client without forcing an unreleased version of this project.

You should be able to use this safely. The release versions are more about the version of daemon. I wouldn't tie too much value to "released" or "unreleased" from the perspective of the client.

**Comment by tamird** [comment]
It's not about my values, unfortunately. Vendoring tools like golang/dep
are opinionated in this regard, so this is a pain in the neck for anyone
downstream of you.

**Comment by stevvooe** [comment]
> Vendoring tools like golang/dep
are opinionated in this regard, so this is a pain in the neck for anyone
downstream of you.

File a bug with `golang/dep`? We use `vndr`, as not all dependencies may follow the one true semver. Could you point me to an example of why this is problematic? Guessing you are talking about [cockroach](https://github.com/cockroachdb/cockroach/blob/master/Gopkg.toml#L26), which seems like several projects require a constraint. Does the tool default to using the latest tag rather than master?

**Comment by tamird** [comment]
> Does the tool default to using the latest tag rather than master?

Yes.

On Feb 6, 2018 18:42, "Stephen Day" <notifications@github.com> wrote:

Vendoring tools like golang/dep
are opinionated in this regard, so this is a pain in the neck for anyone
downstream of you.

File a bug with golang/dep? We use vndr, as not all dependencies may follow
the one true semver. Could you point me to an example of why this is
problematic? Guessing you are talking about cockroach
<https://github.com/cockroachdb/cockroach/blob/master/Gopkg.toml#L26>,
which seems like several projects require a constraint. Does the tool
default to using the latest tag rather than master?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/distribution/issues/2503#issuecomment-363604697>,
or mute the thread

**Comment by stevvooe** [comment]
@tamird That is an awful default, considering the history of the community. ;)

Looks like https://github.com/golang/dep/issues/856 discusses this. I am not sure how to inject this reality into the conversation, so I'm open to suggestions.

I'll see what we can do about a release, but we really want to get the OCI stuff sorted out.

**Comment by xiaods** [comment]
OCI distribution spec should be set high priority score.

**Comment by dmp42** [comment]
We should release a new stable relatively soon. Closing this then.
