### ISSUE TITLE
TLS review/rehaul

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#279]
TLS use in the engine should be reviewed thoroughly.
Specifically, we should:

 * enforce TLS 1.2
 * review garant client code

Reviewing TLS settings for the registry itself is probably a good idea as well.

**Comment by dmp42** [comment]
Relevant issues:

**Comment by stevvooe** [comment]
Filed #280 to require TLS 1.0 and restrict the cipher suites.

**Comment by stevvooe** [comment]
@dmp42 Any specific reason why we would require TLS 1.2 vs 1.0? Is there anything we need to interoperate with that requires 1.0?

I know the suggestion above is 1.2, but @diogomonica's comment suggests 1.0.

**Comment by diogomonica** [comment]
My recommendation for TLS1.0 was based on the lack of time to test compatibility for 1.6. For 1.7 this is my recommendation:

Currently docker.go has a TLS MinVersion of TLS1.0:
```go
tlsConfig.MinVersion = tls.VersionTLS10
```

We should consider changing MinVersion to TLS1.2. I also think Docker should be more opinionated when it comes to CipherSuites:

```go
config := tls.Config{
    MinVersion:               tls.VersionTLS12,
    PreferServerCipherSuites: true,
    CipherSuites: []uint16{
        tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
        tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
        tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
        tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
        tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
        tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA},
}
```

In terms of support, all major servers currently support TLS1.2. This is the reasoning for these choices:

- ECDHE+AESGCM ciphers are selected first. No known attack currently target these ciphers.
- PFS cipher-suites are mandatory.
- SHA256 signature is preferred to SHA-1 in ciphers and certificates.
- AES 128 is preferred to AES 256 because it provides good security, is really fast, and seems to be more resistant to timing attacks.

**Comment by ewindisch** [comment]
@diogomonica we reviewed this before and chose TLS 1.0 based on common use of Python clients (Docker Compose in particular). Similarly, Python did not support decent cipher suites.

**Comment by ewindisch** [comment]
@diogomonica to clarify, this is why we cannot (easily) require TLS 1.2 on the server... but the client would ideally have MinVersion TLS12.

**Comment by amylindburg** [comment]
@stevvooe @NathanMcCauley take a look at this one vis a vis v2.1 Registry

**Comment by dmp42** [comment]
@diogomonica should this be closed? cc @tiborvass

**Comment by tiborvass** [comment]
@diogomonica @dmp42 

Thanks to #13375, we now use the same default versions and ciphers for all registry operations: pull, push, search and login, for all versions: v1, v2, official, private, mirror.

The only "weird" thing is that we use the serverdefault for a client tls config, the reason being that we wanted the TLS settings to be more strict than the clientdefault, even though engine is the registry's client.

Small improvements would be to reuse from tlsconfig, the functions that set up the certs but that's not impacting the TLS version and ciphers.

I would love some feedback on that client-server weirdness (should we rename them differently?), but other than that, if you ever need to change some settings, `tlsconfig` package is where you need to do the change and it will affect all of engine.

By the way we should probably make it its own package under github.com/docker/tlsconfig or something like that so that other projects can benefit from it.

**Comment by diogomonica** [comment]
@tiborvass what exactly do you mean with we use the serverdefault for a client tls config?

**Comment by tiborvass** [comment]
@diogomonica My bad I got the logic backwards, ClientDefault should be stricter than ServerDefault. I opened this PR to fix it: docker/docker#14933

**Comment by stevvooe** [comment]
@diogomonica @tiborvass What have to be met to close this ticket?

**Comment by thaJeztah** [comment]
ping @diogomonica @tiborvass ^^

**Comment by dmp42** [comment]
I consider the original issue fixed.
If there is a need for more specific TLS work, we should open specific tickets for that.
