### ISSUE TITLE
Buildkit documentation: "requires Linux"

### ISSUE THREAD

**Issue by marek-obuchowicz** [docker/distribution#2864]
On the documentation page: https://docs.docker.com/develop/develop-images/build_enhancements/
I can read:
```
Limitations
(...)
 - Only supported on Linux
```

This seems to be confusing. Buildkit works for me on docker-for-mac and I'm almost sure I've seen it working with docker-for-windows as well, as they both run `docker-machine` on linux VM.

**Comment by thaJeztah** [comment]
Looks like this is a documentation issue (related to https://github.com/moby/buildkit) could you open an issue in the documentation issue tracker?

You can open a new issue directly from that page (using the "request docs changes" button on the right-hand side);

<img width="272" alt="screenshot 2019-02-25 at 17 48 36" src="https://user-images.githubusercontent.com/1804568/53353737-ab2df600-3925-11e9-91a2-85a15bb84cf3.png">


Or use this link to create a new issue: https://github.com/docker/docker.github.io/issues/new

I'll close the issue here, but feel free to comment after I closed

**Comment by marek-obuchowicz** [comment]
:+1: thank you, I opened issue as you suggested.
