### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by arun-gupta** [docker/distribution#363]
Link to "doc" is broken. 

It goes to http://docs.docker.com/distribution instead of which does not exist.

**Comment by stevvooe** [comment]
Which link?

**Comment by arun-gupta** [comment]
Last row of the first table at https://github.com/docker/distribution/blob/master/README.md

**Comment by moxiegirl** [comment]
@arun-gupta That link won't work until after the imminent release.  So, please check back on Friday.

**Comment by stevvooe** [comment]
@moxiegirl Shouldn't the link go to the github version of the documentation?

**Comment by arun-gupta** [comment]
@moxiegirl its lame to have the docs with broken link. I'd recommend either remove the hyperlink or update the text to need a hyperlink. Or may be as @stevvooe is suggesting.

**Comment by moxiegirl** [comment]
@arun-gupta it is lame but only a short time lame as we release tomorrow.  

@stevvooe I think it should go to the documentation on the website.  If you would prefer it go to the repo docs, then when you edit the README, you should make it go there.   At this point, I'm going to hold off on doing anything to the AM as I'm running on a 14 hour day and this issue is minor.

**Comment by moxiegirl** [comment]
Hmm I lied, I found a compromise after a nice long walk and another break...hopefully everyone likes it.
