### ISSUE TITLE
push error with tokens

### ISSUE THREAD

**Issue by osallou** [docker/distribution#431]
Hi,
I have implemented a token management tool and ran distribution with token config.
login works fine but there is a strange error at push time on host.
On following error, xx.org is my distribution host name. Token tool is triggered and answer to the Docker client with access approval/. When docker client tries to push to blobs, hostname is modified and duplicated (http://hostname, hostname/v2/....)

    osallou@osallou-ldaptop:~/Development/NOSAVE/docker$ docker  -H 127.0.0.1:2375 push cloud-30.genouest.org/testosallou
    The push refers to a repository [xx.org/testosallou] (len: 1)
    697bf05f9918: Image push failed 
    FATA[0000] Error pushing to registry: Put http://xx.org, xx.org/v2/testosallou/blobs/uploads/f9d001d8-85ec-4871-a138-28af28747ba2?_state=HslchzYfMb0S134swmXyEvauqKzgTK0YRKwg5mXxQ1t7Ik5hbWUiOiJ0ZXN0b3NhbGxvdSIsIlVVSUQiOiJmOWQwMDFkOC04NWVjLTQ4NzEtYTEzOC0yOGFmMjg3NDdiYTIiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDQtMjRUMTQ6MjE6MzAuNTYxNTA3MjU4WiJ9&digest=sha256%3Aa3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4: dial tcp: lookup xx.org, xx.org: invalid domain name 

I use Docker version 1.6.0, build 4749651

**Comment by osallou** [comment]
Last message on distribution is:

    172.17.42.1 - - [24/Apr/2015:14:21:30 +0000] "POST /v2/testosallou/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64

**Comment by osallou** [comment]
Adding a few more logs from Docker ran in debug mode. error occurs at DEBU[0155]

    DEBU[0154] [registry] Calling "POST" https://xx.org/v2/testosallou/blobs/uploads/ 
    DEBU[0154] https://xx.org/v2/testosallou/blobs/uploads/ -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64]] 
    DEBU[0154] Getting bearer token with map[realm:http://yy.org/v2/token/ service:xx.org] for osallou 
    DEBU[0154] http://yy.org/v2/token/ -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64]] 
    DEBU[0154] hostDir: /etc/docker/certs.d/xx.org 
    DEBU[0155] [registry] Calling "PUT" http://xx.org, xx.org/v2/testosallou/blobs/uploads/898c224a-619a-4e53-8c41-aa891aa4e263?_state=5L29dqzldQaPJXEl6lf5U0lXLoJVfbY_r6T-iPu1kMR7Ik5hbWUiOiJ0ZXN0b3NhbGxvdSIsIlVVSUQiOiI4OThjMjI0YS02MTlhLTRlNTMtOGM0MS1hYTg5MWFhNGUyNjMiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDQtMjRUMTQ6NDc6MjUuMzQxMzc3NjI2WiJ9 
    DEBU[0155] http://xx.org, xx.org/v2/testosallou/blobs/uploads/898c224a-619a-4e53-8c41-aa891aa4e263?_state=5L29dqzldQaPJXEl6lf5U0lXLoJVfbY_r6T-iPu1kMR7Ik5hbWUiOiJ0ZXN0b3NhbGxvdSIsIlVVSUQiOiI4OThjMjI0YS02MTlhLTRlNTMtOGM0MS1hYTg5MWFhNGUyNjMiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMTUtMDQtMjRUMTQ6NDc6MjUuMzQxMzc3NjI2WiJ9 -- HEADERS: map[User-Agent:[docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-48-generic os/linux arch/amd64]]

**Comment by osallou** [comment]
Issue could be link to use of X-Forwarded-Host in ./vendor/src/github.com/docker/distribution/registry/api/v2/urls.go

Behind a proxy, X-Forwarded-Host can contain multiple values (http://httpd.apache.org/docs/2.2/en/mod/mod_proxy.html)

**Comment by stevvooe** [comment]
@osallou Could you include the full registry logs?

cc @jlhawn

**Comment by jlhawn** [comment]
@osallou 

I noticed from the logs that your token server appears to be accessed over an insecure connection:

    http://yy.org/v2/token/

Unless it's being contacted over a secure private network, you may want to consider setting up TLS for everything, especially if you are sending any login credentials to that token serve. It also may be that your registry config `auth.token.realm` field needs to be set with an `https` schema instead of `http` if that's what you currently have.

I think you are on the right track in that this may be related to your proxy's forwarded headers. With the `PUT` request going to `xx.org, xx.org` it may be related to the `Location` response  header returned by the previous `POST` request. We should probably add a client debug log in Docker to log this value but for now you can use `curl` to try the `POST` request manually and inspect the `Location` header in the response (may require manually getting a token).
