### ISSUE TITLE
Migrating from docker-registry to 2.0

### ISSUE THREAD

**Issue by thedug** [docker/distribution#437]
I'm running the old version of the registry and am curious if there are any migration instructions.

I'm currently running with the following settings and I'm curious if any of the these values have changed.

I've also been considering using redis and was curious if there are any extra config necessary and if I could just run a vanilla redis container on localhost or if there is more configuration required.

        '-e SETTINGS_FLAVOR=s3',
        '-e AWS_BUCKET={bucket}',
        '-e STORAGE_PATH=/registry',
        '-e AWS_KEY={key}',
        '-e AWS_SECRET={secret}',
        '-e SEARCH_BACKEND=sqlalchemy',
        '-p 80:5000'

**Comment by thedug** [comment]
Note: the links on this storage-drivers page are broken.

https://docs.docker.com/registry/storagedrivers/

**Comment by RichardScothern** [comment]
Hi @thedug .  You can configure the v2 registry with a yaml config file:
https://docs.docker.com/registry/configuration

The S3 and redis configuration instructions are here:
https://docs.docker.com/registry/configuration/#s3
https://docs.docker.com/registry/configuration/#redis

cc @moxiegirl for the storage driver links

**Comment by stevvooe** [comment]
@thedug Thanks you for letting us know about the broken links. You can browse through the repo to get the correct documentation:

https://github.com/docker/distribution/blob/master/docs/storagedrivers.md

**Comment by moxiegirl** [comment]
Thanks folks. I'm hoping to get the links fix out today.

**Comment by denibertovic** [comment]
So if I understand correctly env vars don't work any more for overriding the configuration in the .yml file?

**Comment by RichardScothern** [comment]
@denibertovic : they do.  See https://github.com/docker/distribution/blob/master/docs/configuration.md#override-configuration-options

**Comment by moxiegirl** [comment]
Links fixed in https://github.com/docker/distribution/pull/480

**Comment by stevvooe** [comment]
@thedug I wanted to make sure your questions were covered directly.

> I'm running the old version of the registry and am curious if there are any migration instructions.

Are you migrating data or configuration? Right now, we don't have migration instructions for data, but we will in the future, when provide a V1 deprecation plan. For configuration, the registry v1 configuration isn't a great place to start, since it is pretty different. Using the configuration documentation can help to understand where items are similar, such as s3 configuration.

> I'm currently running with the following settings and I'm curious if any of the these values have changed.

Please see the documentation to compare.


> I've also been considering using redis and was curious if there are any extra config necessary and if I could just run a vanilla redis container on localhost or if there is more configuration required.

This is covered in detail in the configuration documentation. You need to configure the redis connection pool and then point the layercache at redis.

Unless you have any other questions, I'm going to go ahead and close this ticket.

**Comment by denibertovic** [comment]
@stevvooe and everyone. I'm all good. Thanks for your help. Sorry for the late reply but this got lost in my inbox.

**Comment by stevvooe** [comment]
@denibertovic Thank you for following up.

If you're still looking into this, check out docker/migrator.
