### ISSUE TITLE
authorization service certificate path in Dockerfile

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#520]
While configuring registry 2.0, there is an entry "rootcertbundle" under "token" authentication. Where this "rootcertbundle" comes from (inside registry container)?

If we need to add this certificate bundle, then probably we need to add the server certificate bundle from local system using "ADD" instrunction in Dockerfile?

Could anyone please clarify on it?

**Comment by dmp42** [comment]
rootcertbundle is for token based authentication only.

If you want to specify it using the provided Registry image, you should use a mounted volume to make your cert available inside the container from the host, and point to that internal path. No need for a ADD instruction, and no need to override the vanilla image.

**Comment by sourav82** [comment]
Thanks @dmp42

**Comment by AngryHacker** [comment]
Still confused about:

what is a "rootcertbundle"? How can I generate it?

Is there any relation between the "rootcertbundle" and "ca.crt" needed by docker client for a https?

**Comment by dmp42** [comment]
The root cert is the certificate that the token server would use to sign the auth tokens.
It has no relation at all with https on the registry.

Think about it as a "shared secret" between the auth token server and the registry.

Sorry for the documentation is scarce here - will try to make it better in the future.

**Comment by AngryHacker** [comment]
@dmp42 In this way, can it just be a file with a simple string?

**Comment by dmp42** [comment]
No. It must be a public certificate, such as what you would use for nginx / a website.

**Comment by AngryHacker** [comment]
In the auth tokens, the document here https://docs.docker.com/registry/spec/auth/token/#example says that “ the client makes an HTTP request to the following endpoint over TLS using a client certificate with the server being configured to allow a non-verified issuer during the handshake“.

Is it means the certificate is the certificate such as "ca.crt" for https?

And the next is:

"The server first inspects the client certificate to extract the subject key and lookup which account it is associated with. The client is now authenticated using that account."

It means the server verify the user by account and subject key?
But I think the certificate is only for https, and the server should verify the user by username and password, because the client set HTTP Basic Authentication in the request?

**Comment by dmp42** [comment]
@AngryHacker the certificate is used to sign the token, and the token contains the authorization payload.
The user authenticates against the Auth server, not against the registry.
And yes, the certificate is a plain "ca.crt" like.

@AngryHacker Tickets on github are not meant for such conversations.
For discussions like this, the mailing list or irc are the right place.

Thanks.

**Comment by AngryHacker** [comment]
@dmp42  Thanks.
I ask here because I think it's related to this issue, and others maybe confused like me.

**Comment by dmp42** [comment]
@AngryHacker admittedly the documentation is scarce on this...

**Comment by AngryHacker** [comment]
@dmp42 Yesterday I finally succeed in the authorization without cert because I modify the code to let it never verify the token....I think the document about the third step in generating the Json Web token will make me crazy again...

**Comment by kevinsimper** [comment]
@dmp42 Why do it need a certificate to sign the token? Why not just a shared secret like you normally do with JWT?

I can't get the picture of how that certificate has a connection to the authentication server?

It seems a little bit over complicated.
