### ISSUE TITLE
Configuration for http: addr: localhost:5000 does not work

### ISSUE THREAD

**Issue by GittyHup** [docker/distribution#523]
As I was preparing to setup nginx, I went in to modify the config.yml file so the registry would listen for localhost only and not all interfaces as it does by default.

I changed the following:

    http:
        addr: :5000

To:

    http:
        addr: localhost:5000

Now I keep getting these errors below when I try to push an image in my localhost:

    FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get http://localhost:5000/v1/_ping: net/http: transport closed before response was received

    FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get http://localhost:5000/v1/_ping: EOF

    FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get http://localhost:5000/v1/_ping: read tcp 127.0.0.1:5000: connection reset by peer

**Comment by stevvooe** [comment]
It looks like the registry may be bound to a different localhost. Are nginx and the registry in the same container?

**Comment by GittyHup** [comment]
Actually I was doing this before I started to do anything with nginx. Just running the registry image container. When I delete the "localhost", it all starts working again. Don't think it makes a difference, but I am actually mounting my config.yml file from the host to the docker container.

    docker run -d -v ~/my-docker-registry-config/config.yml:/go/src/github.com/docker/distribution/cmd/registry/config.yml -p 5000:5000 registry:2.0

**Comment by stevvooe** [comment]
@GittyHup When you bind to localhost inside the container, the service won't be available outside the container, even though you are specifying the port mapping. When the docker daemon goes to connect, it cannot connect to the port since the service is not bound to the "external" interface of the container. It's the same as if two laptops are sitting on the same WiFi network. A service bound to localhost on laptop A will not be available to laptop B. For the service to be available to laptop B, the service must be bound to an interface available on the WiFi network.

I hope this clarifies the issue. I'd recommend poking around with `nc` on the host machine and maybe `ifconfig` and `netstat` within the running container to try to understand this better.

**Comment by GittyHup** [comment]
Thanks @stevvooe, I suspected that might be the issue. Could please suggest how I would have it listen on localhost only?

**Comment by GittyHup** [comment]
Thanks @stevvooe, I had a feeling that was why. I am guessing I would have to add the localhost to the port configuration when I execute the docker run command.

**Comment by stevvooe** [comment]
@GittyHup Glad to have helped!

Added localhost to the port spec should work but I would recommend playing around. If you have further questions about docker networking, I'd recommend hitting #docker on IRC or the docker-users@dockerproject.org mailing list. They have a lot more experience in this area and will help you get the right solution.
