### ISSUE TITLE
Contradictory DELETE documentation in "Docker Registry HTTP API V2"

### ISSUE THREAD

**Issue by DreadPirateShawn** [docker/distribution#549]
In the "Docker Registry HTTP API V2" doc (docs/spec/api.md), DELETE has two contradictory documentation instructions.

First in "Deleting an Image": "For deletes, `reference` *must* be a digest or the delete will fail."

In the table shortly lower: "Delete the manifest identified by `name` and `reference` where `reference` can be a tag or digest."

Granted, this will likely be revisited in the course of updating the docs for tags as first class citizens (#173), but it'd be good to make sure to clarify all references consistently.

**Comment by RichardScothern** [comment]
mea culpe, I'll update the docs before PR-ing.

**Comment by stevvooe** [comment]
Just to clarify, this is the specification, not the documentation.

@DreadPirateShawn Thank you for filing this issue.

**Comment by stevvooe** [comment]
@DreadPirateShawn Submitted #599. Please confirm this addresses the problem.

**Comment by DreadPirateShawn** [comment]
Looks like it! Covers the one I ran into plus a variety of others -- much obliged.

**Comment by JonathonReinhart** [comment]
I'm trying to implement [image deletion](https://docs.docker.com/registry/spec/api/#deleting-an-image) in my Python registry API. I've read most all of [the API spec](https://docs.docker.com/registry/spec/api/#deleting-an-image) and it is not clear to me exactly what to pass as the *digest* for `reference`. Could someone provide guidance?

I figured since it's arguably still a lack of documentation causing my confusion, that it would be okay to piggy-back on this issue.

**Comment by stevvooe** [comment]
@JonathonReinhart Closed issues aren't really the correct venue for specification clarifications. Please use the mailing list or IRC in the future.

This is covered in the [specification](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image):

> For deletes, reference must be a digest or the delete will fail.
