### ISSUE TITLE
Need info for push/pull notification 

### ISSUE THREAD

**Issue by sourav82** [docker/distribution#559]
I've set up a notification service to capture the notification events while pushing an image to the registry.

Could you please clarify how notifications are generated? I noticed, while pushing an image, notifications having action "pull" also getting generated. 

Also, I was wondering, when the notification for a layer is actually posted, i,e., before pushing a layer or after a layer has been pushed.

What will be the last notification for an image push? Does the last notification always contain a URL pointing to "https://IP:PORT/v2/namespace/repo/manifests/tag" format?

**Comment by stevvooe** [comment]
@sourav82 Notifications are generated when operations against `distribution.Repository` occur.

If there are "pull" notifications generated, that may be a bug. We'd need more information to debug that. This could simply be the client checking status, in which case it will be a "pull" with a HEAD request.

The notifications are generated after the operations are completed.

An image push is a number of operations, including layer checks, layer pushes and a manifest push. The final message should be a push of a manifest type. The url will be the "canonical" url, which will include the digest, rather than the tag. This ensures that you get the exact data associated with the notification.

In the future, if you could keep your issues to single questions or use the mailing list (distribution@dockerproject.org), it would be helpful for us to get you the right answers.

**Comment by sourav82** [comment]
Thanks @stevvooe. Apologies. Next time, will surely follow the guidlines for posting questions.

Yes, for a "push", the "pull" notifications are indeed a HEAD request. It is working like one push followed by one pull (HEAD) and so on until the last push where manifest is pushed.

But the canonical URL in the notification, for the last manifest push, contains "tag" instead of "digest", though, digest is there in a separate field. For below example, for pushing an image "sourav/debian:wheezy" it generates below json -
```json
{
    "events": [
        {
            "id": "c0d2395d-651b-4961-be12-94edc55a7913",
            "timestamp": "2015-05-25T07:09:24.420892134Z",
            "action": "push",
            "target": {
                "mediaType": "application/vnd.docker.distribution.manifest.v1+json",
                "length": 6788,
                "digest": "sha256:82e9163ab80437999db74e290bf8421f7803ed57c34727056b80e372f7b75d9d",
                "repository": "sourav/debian",
                "url": "https://10.227.125.3:5000/v2/sourav/debian/manifests/wheezy"
            },
            "request": {
                "id": "80ba268b-0018-49b1-b4da-5971b0e603cf",
                "addr": "10.227.125.3:41850",
                "host": "10.227.125.3:5000",
                "method": "PUT",
                "useragent": "docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.13.0-43-generic os/linux arch/amd64"
            },
            "actor": {
                "name": "sourav"
            },
            "source": {
                "addr": "0325187311d8:5000",
                "instanceID": "c117bcd3-9e42-498a-8a35-8459b9b482b9"
            }
        }
    ]
}
```

**Comment by stevvooe** [comment]
@sourav82 No need to apologize.

Looks the tag-based URL is a bug. There is actually a TODO in that section of the code. I'll submit a fix in a bit.

**Comment by stevvooe** [comment]
#569 has been submitted to address the notification issue.
