### ISSUE TITLE
version number should reflect tagged version

### ISSUE THREAD

**Issue by mika** [docker/distribution#586]
I'm checking out the latest tag (v2.0.1) and building it via:

````
  % echo $GOPATH
  /go
  % git clone https://github.com/docker/distribution.git
  % cd distribution
  % git checkout v2.0.1
  % go get -v github.com/docker/distribution/cmd/registry
  % godep restore
  % DISTRIBUTION_DIR=/go/src/github.com/docker/distribution
  % GOPATH=$DISTRIBUTION_DIR/Godeps/_workspace:$GOPATH
  % make PREFIX=/go clean binaries
```

But then the version information still reports v2.0.0:

````
% /go/bin/registry -version
/go/bin/registry github.com/docker/distribution v2.0.0+unknown
````

I'd expect that to be v2.0.1 (or if I'm holding godep wrong - since 'godep get' inside the git repository doesn't seem to work - then at least v2.0.1+unknown or similar). Am I'm holding it wrong?

**Comment by dmp42** [comment]
You probably want to synch the version info from the git info.

Have a look into the makefile here: https://github.com/docker/distribution/blob/master/Makefile#L16

**Comment by stevvooe** [comment]
Please read the document on [building](https://github.com/docker/distribution/blob/master/docs/building.md). The version number is only set If the `Makefile` is used, since we do this through the linker. I suspect that the version you are running was not actually built by the `Makefile`. With the flow you're using, calling `go get` is not necessary but may have built the binary.

What is the output of each command?

**Comment by mika** [comment]
@dmp42: I noticed ` ./version/version.sh` and tried to play with it, but manually running it as part of the way I built the binary doesn't seem to work, I assume `version/version.go` should be kept up2date if it's part of the git repository with the according version tag information?

@stevvooe I did read the `building` document of course, but I assumed that "Build the development environment" would be enough, especially since the version number is event explicitly mentioned there. :)
I also tried to follow the "Repeatable Builds" steps but this doesn't work for me, it looks like it's not using the pinned versions from Godeps/Godeps.json, because I'm running into build failures which I assume shouldn't happen with v2.0.1? Output available here: https://gist.github.com/mika/1c473742bcfb566359ab

Output of each command from my build process: https://gist.github.com/mika/b8422537dc363213ba98

**Comment by stevvooe** [comment]
@mika From the output, it looks like the GOPATH has a newer version the distribution packages. The build failures indicate that you're trying to build the v2.0.1 code base from the master package. It is possible that a prior build is exposing the new interfaces when you need to build against the old one. Make sure there isn't a fresh checkout somewhere in the GOPATH and delete the pkg directory if that doesn't help.

Looking closer at the output, it looks like the problem may be that you haven't properly checked out the code base in the Go workspace:

```
_/home/mika/docker-distribution
_/home/mika/docker-distribution/cmd/dist
```

Generally, this is covered when reading the build instructions and issuing the following command:

```
go get github.com/docker/distribution/cmd/registry
```

This will checkout the distribution project into the GOPATH and you can develop there. This will likely fail when building but that doesn't matter. Once that is complete, you can change into that directory (`$GOPATH/src/github.com/docker/distribution`), checkout the version you want to build and work from there.

Please make sure you are following [how to write Go code](https://golang.org/doc/code.html) when setting up the development environment. _I'll add a section to the building instructions to make this is apparent._

Regarding `./version/version.sh`, please read the comments carefully. In particular, this one:

```
// Version indicates which version of the binary is running. This is set to
// the latest release tag by hand, always suffixed by "+unknown". During
// build, it will be replaced by the actual version. The value here will be
// used if the registry is run after a go get based install.
```

The value generated there is simply so that builds that don't have the linker set the version get a reasonable version number. It can never be checked in correctly, since the very act of making a commit would change the version number. The real version number is detected in this line of the `Makefile`:

```
GO_LDFLAGS=-ldflags "-X `go list ./version`.Version $(VERSION)"
```

**Comment by stevvooe** [comment]
@mika I've added clarification to the build instructions #591.

**Comment by mika** [comment]
@stevvooe thanks for your assistance, this clarifies it for me! I got confused by the build failure of  `go get github.com/docker/distribution/cmd/registry` (see https://gist.github.com/mika/cf5ebd90fadad9aa90c0 which is https://github.com/docker/distribution/issues/573) and didn't think about just switching to `$GOPATH/src/github.com/docker/distribution` to continue with according builds. :)

So this is what worked for me:

````
# GOPATH=/go go get golang.org/x/tools/cmd/vet # this was additionally needed

% export GOPATH=/go
% export PATH=$PATH:/go/bin
% go get github.com/docker/distribution/cmd/registry # ignoring mentioned build failure
% go get github.com/tools/godep github.com/golang/lint/golint
% cd $GOPATH/src/github.com/docker/distribution
% git checkout v2.0.1
% GOPATH=`godep path`:$GOPATH make
% /go/src/github.com/docker/distribution/bin/registry -version
/go/src/github.com/docker/distribution/bin/registry github.com/docker/distribution v2.0.1.m
````

As follow up to "Regarding ./version/version.sh, please read the comments carefully. [...] It can never be checked in correctly, since the very act of making a commit would change the version number. ": I don't really see the problem since version/version.go is a file being under gits version control. Before tagging a new release just raise the version number in version/version.go to the version you want to tag, so it would be setting "v2.0.1+unknown" in version/version.go in one commit, then tag this commit as "v2.0.1" and it's clear then? This is the workflow I'm used to if the version number is supposed to be hard-coded somewhere.

**Comment by stevvooe** [comment]
That build failure is obnoxious. It is due to the azure drivers. We may want to disable them by default, since `go get` should always work.

> As follow up to "Regarding ./version/version.sh, please read the comments carefully. [...] It can never be checked in correctly, since the very act of making a commit would change the version number. ": I don't really see the problem since version/version.go is a file being under gits version control. Before tagging a new release just raise the version number in version/version.go to the version you want to tag, so it would be setting "v2.0.1+unknown" in version/version.go in one commit, then tag this commit as "v2.0.1" and it's clear then? This is the workflow I'm used to if the version number is supposed to be hard-coded somewhere.

We do not hardcode the version number and the one present there is just to provide a reference. When we see it, we know that it was built after that commit and definitely not with the Makefile. The version number is set by the tag name, which is PGP signed. For my current environment, the version is `v2.0.0-168-gb9eeb32`. If I make a commit, that will change, so it cannot be committed accurately.

Really, this doesn't matter at all. We're going to take a slightly different approach for the next release.

**Comment by mika** [comment]
* Stephen Day [Wed Jun 03, 2015 at 06:06:47PM -0700]:

> That build failure is obnoxious. It is due to the azure drivers.
> We may want to disable them by default, since `go get` should
> always work.

Sounds good, thanks.

> We do not hardcode the version number and the one present there is
> just to provide a reference.

Sure, I just recommended that it might be good to raise the version
number when tagging a new release so the reference is more accurate.

> When we see it, we know that it was built after that commit and
> definitely not with the Makefile.

Agreed and understood.

> The version number is set by the tag name, which is PGP signed.

This doesn't seem to be the case though (or we're still talking
about different things? :)). But both master as well as the v2.0.1
tag contain 'v2.0.0+unknown', while that could (and IMHO should) be
'v2.0.1+unknown' nowadays (and that's all I care about and am asking
for, but of course feel free to disagree and ignore it).

> For my current environment, the
> version is `v2.0.0-168-gb9eeb32`. If I make a commit, that will
> change, so it cannot be committed accurately.

Sure.

> Really, this doesn't matter at all. We're going to take a slightly
> different approach for the next release.

Ok :)

regards,
-mika-
