### ISSUE TITLE
TagNameRegexp matches too many strings

### ISSUE THREAD

**Issue by bwb** [docker/distribution#587]
Distribution does not use the same regexp as Docker to validate tags. Any code that validates tag names with `v2.TagNameRegexp` accepts invalid strings. For example, these strings match Distribution's tag name regexp:

* `drop table t;`
* `$1.23`
* `!@#$%^&*(tag)`

[Docker](https://github.com/docker/docker/blob/master/graph/tags/tags.go)
```go
var (
	//FIXME this regex also exists in registry/v2/regexp.go
	validTagName = regexp.MustCompile(`^[\w][\w.-]{0,127}$`)
)
```

[Distribution](https://github.com/docker/distribution/blob/master/registry/api/v2/names.go)
```go
// TagNameRegexp matches valid tag names. From docker/docker:graph/tags.go.
var TagNameRegexp = regexp.MustCompile(`[\w][\w.-]{0,127}`)
```

I know that the code responsible for tags is being refactored. Distribution and Docker should not accept different sets of tags.

**Comment by stevvooe** [comment]
@bwb The only difference here is the anchoring. `TagNameRegexp` is used to build higher-level productions where anchoring doesn't make sense, such as part of a route definition. For use cases where you're matching arbitrary strings, we do have "anchored" versions, such as [RepositoryNameComponentAnchoredRegexp](http://godoc.org/github.com/docker/distribution/registry/api/v2#pkg-variables), but this was omitted for tag names, since we aren't using it.

Do you have any examples of bugs caused by this difference within distribution?
What are you trying to do that cannot be achieved without a change here?

**Comment by bwb** [comment]
I'm not aware of any bugs caused by this difference within distribution.

I took the comment "TagNameRegexp matches valid tag names" literally, and used TagNameRegexp to validate tags outside of distribution. I paid little attention to the regexp value, until my tests failed.

**Comment by stevvooe** [comment]
@bwb Would it help in your task to add an anchored version? Do you mind submitting a small PR to accomplish this?

Really, we need a strong type for tags, protected by a `ParseTag` function.

**Comment by stevvooe** [comment]
@bwb  poke.

**Comment by dmp42** [comment]
@bwb ping

**Comment by stevvooe** [comment]
Added `TagNameAnchoredRegexp` (see http://godoc.org/github.com/docker/distribution/registry/api/v2#pkg-variables).
