### ISSUE TITLE
Azure backed registry heavily leaks memory

### ISSUE THREAD

**Issue by jesper** [docker/distribution#620]
Using registry 2.0.1.

I discovered this memory leak after a registry crash that occurred while pushing several images to my private registry: https://gist.github.com/jesper/25231332f99c92393023

After re-starting the registry, I ran "docker stats registry" and observed the memory usage. Each push to the registry slowly increases the memory usage until it finally falls over. Even if the images have not changed, the memory usage still grows on each push attempt.

**Comment by dmp42** [comment]
ping @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
ack I can reproduce the behavior, I'll be back with a fix.

**Comment by ahmetalpbalkan** [comment]
I think I found out the root cause. In the Azure SDK, we didn't `defer resp.Body.Close()` in some hot code paths (i.e. upload blob) by mistake and apparently the connection just stays there dangling, gets a hold to the 4 MB chunks it uploads.

I'm going to add all the missing defer statements to the Azure Go SDK today and will work on updating the vendored package today.

**Comment by dmp42** [comment]
@ahmetalpbalkan thanks a lot for the super fast reaction here and for taking care of this.
You rock! :)

**Comment by ahmetalpbalkan** [comment]
Fix at #623.

**Comment by ahmetalpbalkan** [comment]
@dmp42 you guys are the ones really rock everyday!

**Comment by jesper** [comment]
Thanks so much - you folks are amazing! <3
