### ISSUE TITLE
Discrepancy in Notification format

### ISSUE THREAD

**Issue by shreyu86** [docker/distribution#665]
I am trying to hook up a notification service to hipchat/slack that alerts a group on push from our CI server
as per https://github.com/docker/distribution/blob/master/notifications/event_test.go#L28 the notification event should contain the tag that has been pushed
but when I see the notification body I do not see the tag instead I see the SHA digest, for example: https://gist.github.com/shreyu86/ecded0f6b26bf20c8911#file-gistfile1-json-L12
did the format for the notification change? I am using the following registry config: https://gist.github.com/shreyu86/334fd5f92245e1d0191b

**Comment by stevvooe** [comment]
@shreyu86 If you are looking for the tag of manifest, it is in the manifest itself. Use the URL to download it and you'll be able to access it.

The tests are simply testing that the format is not tampered with. The format of the urls is not part of that particular unit test. Originally, pre-2.0 release, we had included the tag, since this was the only supported way to fetch manifests. With the advent support for pull by digest, we changed to a digest reference for the notification URL (again, pre release). These urls are the only way to uniquely fetch the exact resource that was pushed. If using a tag url, by the time the event is received, a different manifest could be the value of that tag.

Note that we don't send a notification separately for the tag since tag objects aren't yet represented as unique entities.

**Comment by shreyu86** [comment]
@stevvooe thanks for the clarification, this makes a lot of sense, I was confused and then looked at the tests to see how canonical format looks like which led to my curiosity, definitely manifest contains the source of truth and shall use it for creating notifications.

**Comment by stevvooe** [comment]
@shreyu86 Great, I'll go ahead and close.
