### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by berlincount** [docker/distribution#703]
Will there be a new release some time soon?

Thanks! :)

**Comment by dmp42** [comment]
Yes, there will be, soon :-)

We use the milestones thingie over here: https://github.com/docker/distribution/milestones and some attemptive roadmap here: https://github.com/docker/distribution/blob/master/ROADMAP.md#registry

True, bunch of new cool fixes and stuff in master since the release - and they will be released soon!
