### ISSUE TITLE
Storage driver TestStatCall modtime granularity

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/distribution#71]
Currently tests for Stat() call require modtime to be **exactly** to the same be with the current time. On cloud machines, that simply can't be the case and clocks can be several seconds off. 

```go
	if start.After(fi.ModTime()) {
		c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
	}

	if fi.ModTime().After(expectedModTime) {
		c.Errorf("modtime %s after file created (%v)", fi.ModTime(), expectedModTime)
	}
```

Even if the time spent on the wire gets longer, the test case would simply fail:
I was testing this with azure driver and encountered a failure due to one-second off, here's that:

    c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
    ... Error: modtime 2015-01-16 20:10:02 +0000 UTC before file created (2015-01-16 12:10:03 -0800 PST)

This should probably have some ɛ=±5s around the modtime value, because the point is to verify mtim works and sane. In this case even ±60s should be ok. How about:

```go
	if start.Add(time.Second*epsilon).After(fi.ModTime()) {
		c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
	}

	if fi.ModTime().After(expectedModTime.Add(time.Second*epsilon)) {
		c.Errorf("modtime %s after file created (%v)", fi.ModTime(), expectedModTime)
	}
```

lmk if you agree and I can send the patch. cc: @stevvooe

**Comment by stevvooe** [comment]
Indeed, this is a problem. Rather than using an ɛ, would it be possible to ensure that modification times are monotonic? For example, could the test be changed to create a file, change it, then check that the new modification time is after the first one?

**Comment by ahmetalpbalkan** [comment]
@stevvooe not really, that wouldn't work either. Cloud storage systems set the mtime from the frontend storage node hit by load balancer. And these frontend nodes can really have different times. Therefore it's not guaranteed that if you modify the file, it will get a newer mtime.

**Comment by stevvooe** [comment]
How can one implement coherent caching for data upon systems without monotonic clock guarantees? This basically breaks `If-Modified-Since` requests. I'm also not sure if you can generalize this behavior to  "cloud storage systems", since these tests are working on s3. Yes, there can be some clock skew, but ntp can get the machines within a second of each other. Also, if a storage node can change a block of data, can it not read the mtime from the old entry and make sure to give it a time that is after it?

Have you tried this on azure? What failures are you seeing?

**Comment by stevvooe** [comment]
cc @BrianBland

**Comment by ahmetalpbalkan** [comment]
@stevvooe Windows ntp guarantee is unfortunately 30 seconds iirc :-) and if-modified-since is a best effort method. Also the storage frontend node doesn't/may not care that it's writing an older date.

Generally Azure won't be bad. It will probably be +-2 seconds at most and the problem I saw was only 1 sec difference, which can totally occur in s3 as well when you start uploading in the last milliseconds of the second.

I think checking for +-5 seconds or sleep-and-modifying will make tests much less flaky. Tests definitely shouldn't fail with this and sleeping 10-20 secs in this case appears to be fine.

**Comment by stevvooe** [comment]
@ahmetalpbalkan Let's go with the sleep + modification approach. 

> if-modified-since is a best effort method

What do you mean by this? Do you mean that it's best effort in azure or the header is best effort? The issue here is that if something is modified and a client may continue to use an old version if the mod times are inverted.

**Comment by ahmetalpbalkan** [comment]
@stevvooe what you're talking about is probably the `ETag` header (exists in both s3/azure) and it behaves like a checksum (based on revision and contents). Programmatically caching such entities is done through ETag rather than If-Modified-Since/Last-Modified and its usage is more common in browsers. I'm not sure it's the right thing for this use case.

Sleep and modify is probably better here.

**Comment by stevvooe** [comment]
@ahmetalpbalkan I'm familiar with the difference between `ETag`/`If-None-Match` and `If-Modified-Since`/`Last-Modified`. They are different methods for supporting modification checks on content. Browsers support both and most edge caches (such as cloudfront, backed by s3) support both. The advantage to `Last-Modified` + `Expires` is that one can avoid a round trip to check for changes.

The registry should support both, depending on the use case.

**Comment by ahmetalpbalkan** [comment]
You're right. Closing this to follow up at #77.
