### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by nicbarker** [docker/distribution#754]
Hi guys,
I'm having some trouble with the provided implementation of distribution through compose (contrib/compose)  

I'm running on a $5 DO node with 20gb of disk space, 2.2 of which is used before running docker-compose up:

<img width="378" alt="screenshot 2015-07-26 10 55 38" src="https://cloud.githubusercontent.com/assets/2264338/8892047/1c7270b6-3385-11e5-9039-38dc1ab5a996.png">

Compose pulls the FS layers, starts registry v1, then tries to start registry v2, and promptly runs out of disk space:

<img width="743" alt="screenshot 2015-07-26 10 56 01" src="https://cloud.githubusercontent.com/assets/2264338/8892049/39a92c10-3385-11e5-8efb-5c3445f5a4c3.png">

The end result is that only registry v1 is running, and all 20gb of disk space is used:

<img width="375" alt="screenshot 2015-07-26 10 56 07" src="https://cloud.githubusercontent.com/assets/2264338/8892050/6585b970-3385-11e5-85bf-6a23aaed7e39.png">

Is this expected behavior - does distribution need more than 20gb of disk space just to start with no images?

**Comment by dmp42** [comment]
Hi,

I strongly suggest you follow the documentation instead of whatever is in the contrib folders, specifically starting with https://github.com/docker/distribution/blob/master/docs/deploying.md

In particular, why would you need to run registry:1? Furthermore, the contrib folders will build the images instead of using the official ones (like the docs encourage you to use), thus consuming way more disk space.

So, no, the registry:2 image should not need more a couple hundred MB.

Hope that helps - let me know (usually on irc #docker-distribution is a better place for support questions).

**Comment by nicbarker** [comment]
Hi,
Thanks for the pointers. I was lazily hoping for a magical "docker-compose up" just to test out distribution + nginx before I dived in myself. I'll go through the docs and do it properly.

**Comment by dmp42** [comment]
Here you have one such all-in-one-lazy compose file:

https://github.com/docker/distribution/blob/master/docs/authentication.md#setting-things-up

(careful about NOT using bcrypt to generate the password - doc caveat for now)
