### ISSUE TITLE
Soft delete a repository

### ISSUE THREAD

**Issue by dmp42** [docker/distribution#761]
This feature should provide a way to soft-delete all elements being part of a given foo/bar repository (all manifests and all layers references).

It's understood that if the user does simultaneously push, unexpected things will happen.
It's understood that the hub to use that feature is expected to "lock" the repository.

**Comment by stevvooe** [comment]
@dmp42 Registry API doesn't really have the concept of a repository, other than the named location of the data. For example, we don't have paths like `/v2/<name>`, since it requires trailing path elements to "fix" the name. To delete the repository, delete all of its contents, from an API perspective.

When I last spoke to the hub team, they agreed to simply issue a delete of the directory directly to the backend. What happened to this agreement?

**Comment by dmp42** [comment]
> When I last spoke to the hub team, they agreed to simply issue a delete of the directory directly to the backend. What happened to this agreement?

What makes you think this changed?

**Comment by stevvooe** [comment]
This is a duplicate to #225. Closing for now. If is different. Please reopen.
