### ISSUE TITLE
Unclear sentence in API docs

### ISSUE THREAD

**Issue by petervo** [docker/distribution#916]
This sentence in the API docs seems to contradict itself: 

"Applications can only determine if a repository is available but not if it is not available."

I'm really not sure what the intent is otherwise i'd open a PR. Anyone able to clarify?

**Comment by stevvooe** [comment]
@petervo The sentence is accurate. It effectively means that if the repository is in the data set, you can be reasonably certain it is available in the repository (save for deletes, downtime, etc.). The absence of a repository from that data set does imply that it is not available.

This allows registries to serve repositories that may be the result of upstream operations, such as those running as proxies. For example, locally, the registry may have repository "A" and "B", but upstreams i and j may have repositories "C" and "D" respectively. With this language, the registry is only required to report "A" and "B", since "C" and "D" may not be available until an upstream request is made.

This avoids registries having to make complex upstream queries and dataset assemblies in cases where it may not make sense. We relax these requirements for this API call to ensure that a distributed version is actually implementable. With tighter data consistency guarantees, these kind of applications become impossible or prohibitive to implement.

**Comment by petervo** [comment]
Thanks, that makes sense, i misread it. If I think of a better way to say that, I'll open a PR.

**Comment by stevvooe** [comment]
@petervo No problem. I apologize for the confusing but accurate wording.

There may be a way to communicate this with the more familiar, "if and only if..." language, but I am not sure if it should be more clear. There is a section that does go into the reasoning I provided above that should help the reader to understand but it seems to not go far enough.

Any suggestions are welcome.

**Comment by thaJeztah** [comment]
@moxiegirl maybe you have ideas on how to rephrase that sentence?
