### ISSUE TITLE
Returning nil, nil from a method is never acceptable

### ISSUE THREAD

**Issue by stevvooe** [docker/distribution#983]
Atrocious:

https://github.com/docker/distribution/blob/master/registry/client/repository.go#L291

@dmcgowan @aaronlehmann

**Comment by AdoHe** [comment]
@stevvooe Guess we can let `handleErrorResponse` to handle this `404` situation.

**Comment by dmcgowan** [comment]
This appears to have been originally added for the proxy cache support. Not sure what should be returned in this case, if there an error type already defined for this?

@RichardScothern wdyt?
https://github.com/docker/distribution/commit/48a2010ac32c21ef207a32877279d436cc39b4ae

**Comment by RichardScothern** [comment]
The `nil, nil` represents a manifest that was not fetched due to a conditional http request indicating that the current manifest is the latest version for the given tag.   So there is no error, but the only way to indicate this happened is returning a nil manifest.

Without changing the signature of the function the only option is to return an error indicating that the requested manifest is the latest, even though this isn't an error case.

**Comment by stevvooe** [comment]
Typically, we would represent this with an error value. We may want to have a special error code  `ErrNotModified` to represent this condition for conditional calls to `GetByTag`. Optionally, we should implement this behavior with an injectable cache that tracks etags for values of tags. I am not sure how realistic this is for the proxy use case.
