### ISSUE TITLE
Push to v2 registry with local storage location failed

### ISSUE THREAD

**Issue by jerrykwchan** [docker/distribution#992]
Hi,

I'm using docker registry version 2.1.1/docker client 1.8.2.  I started the registry with the following parameter
docker run -d -p 5000:5000 --name bregistry -v `pwd`/data:/var/lib/registry registry:2

When I push an image to the registry, I got the following error
[otter@volcano registry]$ docker push volcano:5000/hello-world
The push refers to a repository [volcano:5000/hello-world] (len: 1)
Sending image list
Error: Status 503 trying to push repository hello-world: "{\"errors\":[{\"code\":\"UNAVAILABLE\",\"message\":\"service unavailable\",\"detail\":\"health check failed: please see /debug/health\"}]}\n

If I start registry withour the "-v" option, the push completed successfully.  Am I miss anything?

Also, how can I access the /debug/health?

regards,
Jerry

**Comment by jerrykwchan** [comment]
I add "--privileged" option in docker run command and I can push to the registry successfully.

**Comment by kopax** [comment]
how did it solved your probleme ?

I have tried also, it gave me the following on startup :

   flag provided but not defined: -privileged
   usage: /bin/registry <config>
   ...

**Comment by jerrykwchan** [comment]
Here is how I start my registry
docker run -d -p 12000:5000 --name appregistry --privileged -v /data/imagestore:/var/lib/registry -v /nfs/home/packagingCerts:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/cert.pem -e REGISTRY_HTTP_TLS_KEY=/certs/key.pem registry:2
By the way, the user I used to start registry is part of "docker" group.

**Comment by kopax** [comment]
Thanks, I am not sure what does the `--privileged` does, but it didn't solve this error.
I had to remove image and rebuild.
Btw are you using basic auth behind a nginx proxy or straight from the registry (or both) ?

**Comment by jerrykwchan** [comment]
I run the v2 registry as container in my docker host.  There is no reverse proxy in between.

**Comment by stvdilln** [comment]
`
curl --insecure https://registry.service.consul\:5001/debug/health

{"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}
`

Replace http or https appropriately.  It doesn't give you much more than you already have "docker logs" against the registry container shows me more.

**Comment by jatinchhabra1** [comment]
i think --privileged mode give super admin privilege which enables you to access /var/lib directory. Only think you should do is to link /tmp volume rather then /var/lib

Please update if that  works !! cheers

**Comment by stevvooe** [comment]
> Only thing you should do is to link /tmp volume rather then /var/lib

If you do this, your images will be gone on restart.

This looks like a permissions issue for the volume. @jerrykwchan solved it with `--privileged` because it ran the container as root (or docker), giving access to the `/var/lib/registry` volume.

The trick here is to ensure that the registry has access to `/var/lib/registry`. Either `/var/lib/registry` should be owned by the registry user, or as part of the group that provides write access to the volume. This can be done with [`-u`](https://docs.docker.com/engine/reference/run/#user) set to the user that owns `/var/lib/registry`.

**Comment by c4milo** [comment]
@stevvooe, I'm running into this same problem but using S3 backend instead. It starts healthy and after 15 to 30 seconds it goes to unavailable. The log doesn't say much neither /debug/health, so I'm clueless as to why could be causing the problem.

**Comment by stevvooe** [comment]
@c4milo Please avoid commenting on closed issues. 

Also, the root cause in this case was filesystem permissions. The main issue your seeing is likely a s3 configuration or connectivity issue. `/debug/health` should have an error pointing to something. There may also be hints in the logs. If that doesn't help, please open a new issue.

**Comment by ianrossi** [comment]
I am also seeing this exact same issue using a Gitlab container registry with an S3 backend: https://gitlab.com/gitlab-org/gitlab-ce/issues/19047

**Comment by stevvooe** [comment]
@ianrossi Did you do as the error message asked and check `/debug/health`?

**Comment by ianrossi** [comment]
@stevvooe So, first things first :)  It's good for this to be posted in this issue, because what I experienced is what happens when the registry server (Gitlab in this case) loses Internet access. Once restored the issue was resolved.

However, to answer your question @stevvooe, I curled that address and I got pretty much the same response, that the health check failed. I couldn't find out how to turn on the debug port in Gitlab through their docs, so I had no way to actually curl that URI. But thanks so much for responding.

**Comment by stevvooe** [comment]
> @stevvooe So, first things first :) It's good for this to be posted in this issue, because what I experienced is what happens when the registry server (Gitlab in this case) loses Internet access. Once restored the issue was resolved.

This, actually, is the right behavior! :)

Presumably, the lack of connectivity would have caused the storage to be inaccessible and triggered the health check.

> However, to answer your question @stevvooe, I curled that address and I got pretty much the same response, that the health check failed. I couldn't find out how to turn on the debug port in Gitlab through their docs, so I had no way to actually curl that URI. But thanks so much for responding.

Indeed. Due to the level of information available in the `/debug/xxx` endpoints, mounting them on the same server as the registry is likely to leak sensitive data.

There _should_ be an associated log message for the failed health check. Do you have the registry logs from when the failure happened?

**Comment by ianrossi** [comment]
Yes, I do, but I believe they were only at info level and I couldn't find out how to set them to debug level. I can take another look.
